### ISSUE TITLE
Layout bugs on some devices

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#1]
There are some strange layout bugs, where texts are cut off although there is enough space available, on some devices: 

<img src="https://user-images.githubusercontent.com/67682506/122280049-0e723680-cee9-11eb-88e2-af39e2d5c734.jpg" width="300">
<img src="https://user-images.githubusercontent.com/67682506/122280054-103bfa00-cee9-11eb-8f95-1951f6d828a9.jpg" width="300">
<img src="https://user-images.githubusercontent.com/67682506/122280057-10d49080-cee9-11eb-8c6d-4d0b6f427566.jpg" width="300">

CovPassCheck (text in offline-modus box):
<img src="https://user-images.githubusercontent.com/67682506/122275969-986bd080-cee4-11eb-811d-6ce2a2a9939d.png" width="300">

Device: iPhone XS

**Comment by timokoenig** [comment]
We adjusted the layout in the next minor version but I will double check those screens

**Comment by timokoenig** [comment]
I checked it again and this also changed in the next minor version

**Comment by timokoenig** [comment]
Version 1.3 just has been released in the AppStore which fixes the issue

**Comment by Ein-Tim** [comment]
Confirm fix.
