### ISSUE TITLE
Recode in SwiftUI to optimize performance?

### ISSUE THREAD

**Issue by scholzf98** [Digitaler-Impfnachweis/covpass-ios#10]
We can heavily increase the performance by rewriting the project in SwiftUI. The transition is not hard at all and since this project is open source everyone could help!

**Comment by visualication** [comment]
Since its a requirement to support iOS 12 its not possible to use SwiftUI

**Comment by timokoenig** [comment]
This might be an option when we drop iOS 12 but not as long as we need to support that version
