### ISSUE TITLE
CovPass Check App V 1.15 on iOS - inconsistent certificate status on 2 different iPhones scanning the same certificate

### ISSUE THREAD

**Issue by Ron-70** [Digitaler-Impfnachweis/covpass-ios#102]
## Technical details

- Device name: iPhone 6 / iPhone SE (2020)
- OS version: iOS 12.5 / iOS 14.6
- App version: CovPass Check App Version 1.15

## Bug Description

Using the CovPass Check App V 1.15 for scanning the same EU COVID Certificate on 2 different iPhones gives different results for the certificate status.

Screenshot - iPhone 6 running CovPass Check App V 1.15 on iOS 12.5:
![grafik](https://user-images.githubusercontent.com/52568084/149943610-cf861407-58d6-4920-b0f5-dde76e427d83.png)

Screenshot - iPhone SE running CovPass Check App V 1.15 on iOS 14.6:
![grafik](https://user-images.githubusercontent.com/52568084/149943963-a86faa26-120b-48c0-a6b3-cfa595729aa4.png)

## Expected behaviour

Same consistent certificate status (in this case "valid certificate") on both iPhones when I scan the same certificate.

Please check what causes this issue.

**Comment by Kurt57** [comment]
Hi @Ron-70 

Thank you. can you please compare the timestamps in the manual update rules page and post them here.

**Comment by Ron-70** [comment]
Hi @Kurt57 

Can you please descibe which timestampf you mean and where to find them?

**Comment by Kurt57** [comment]
In the CovPass Check App startpage on the right tip corner you will find a "?". After tap on the you will be navigated to the information page. Tap on the last point "Update rule set". On the new page "Update rule set" you will find a blue box where two timestamp should be there. If this is missing never and update is done. If there are timestmap please share this. If you able better for both devices screenshot of that page.

**Comment by timokoenig** [comment]
There was a similar issue yesterday: https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/100

**Comment by Ron-70** [comment]
Hi,

I did a manual update now on both iPhones and now both are showing the same consistent result - a valid certificate.
So the problem is solved. Thank you.
