### ISSUE TITLE
App uses wrong vaccine value set

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#109]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The iOS app uses an outdated static value set for vaccine names that results in wrong names, e.g. `COVID-19 Vaccine Moderna` instead of `Spikevax...`

## Steps to reproduce the issue

1. Import vaccination certificate with "Moderna" vaccine
2. Go to item detail view
3. Check the vaccine name

## Expected behaviour

App should use the dynamically loaded vaccine names and not the static list.

## Possible Fix
Remove old static list -> https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/main/Source/CovPassCommon/Sources/CovPassCommon/Resources/DGC-schema/vaccine-medicinal-product.json

Change mapped file in https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8b25bcfcdc0f108f8c74179a09e5ae1849f2b344/Source/CovPassApp/Source/Scenes/Certificate%20Item%20Detail/CertificateItemDetailViewModel.swift#L118 to use value set `vaccines-covid-19-names`

## Additional context

Related ticket https://github.com/Digitaler-Impfnachweis/covpass-android/issues/124#issuecomment-1017209563

**Comment by timokoenig** [comment]
Still not fixed with version 1.18

The app displays wrong vaccine names (and now with new vaccines those names are even missing). I would consider this a critical bug

**Comment by molk** [comment]
> Still not fixed with version 1.18
> 
> The app displays wrong vaccine names (and now with new vaccines those names are even missing). I would consider this a critical bug

https://github.com/Digitaler-Impfnachweis/covpass-ios/commit/30282974ef70665adbe2055713bcb2646cfb797e#diff-38bba4f99dce46635c2649d5ba3413b99303d68bd06fabd26f564208369d8c42R1

this  looks okay, doesn't it?

![grafik](https://user-images.githubusercontent.com/816104/155039669-059aa8fa-f13e-40cf-9f95-9c6c4fc546a6.png)

(iOS v1.18(9))

**Comment by Ein-Tim** [comment]
The released version shows version 1.18 (1).
Maybe this is the difference?

**Comment by timokoenig** [comment]
And exactly there is the problem, vaccine is not displayed correctly.

If the correct one is being used it would display the following value:

```
    "EU/1/21/1618": {
      "display": "Nuvaxovid",
      "lang": "en",
      "active": true,
      "system": "https://ec.europa.eu/health/documents/community-register/html/",
      "version": ""
    },
```

**Comment by alexcimander** [comment]
Hey everyone,

the "dynamic reload" of the right valuesets is currently in development. However the different wordings are no blocker to scan the certificates into the app. Rule-Checks are made using the "dynamic" value-sets provided by TSI - so no rule checks will fail based on the wording within the certificate details.

Thank you for the discussion!

**Comment by timokoenig** [comment]
Not sure what needs to be in development because everything is already implemented. This is just a one minute task with search&replace and then delete the old file. I even posted the solution in my original post.
