### ISSUE TITLE
Missing translation for EN

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#110]
https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8cfce4ca8ccfbdc6d97938a7656e2847b59683d0/Source/CovPassApp/Source/Scenes/ValidationService/ConsentExchange/ConsentExchangeViewModel.swift#L41

**Comment by timokoenig** [comment]
Still not fixed with version 1.18

**Comment by alexcimander** [comment]
Hi Timo,

fix will be part of one of the next releases. Thank you!

**Comment by timokoenig** [comment]
closing; fixed for version 1.35
