### ISSUE TITLE
Incorrect date format on US iPhone when setting the app language to German

### ISSUE THREAD

**Issue by stephanadler1** [Digitaler-Impfnachweis/covpass-ios#111]
## Avoid duplicates
* [✓] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [✓] Bug is not already reported in another issue

## Technical details

- Device name:
- OS version: 15.2.1
- App version: 1.16 (2)

## Describe the bug

When switching the application language to 'German' on a US iPhone, the formatting of dates and times are still using the en-us localization settings of the phone, e.g. 1 Nov. 2021 is rendered as 11/1/2021 instead of 1.11.2021. This is very confusing for people in Germany trying to validate the data visually instead of using the validation app, which during my visit, was only used twice.

## Steps to reproduce the issue

1. Use an iPhone configured for the US market. Could potentially be reproduced on a German iPhone configured for US language settings too.
2. Install the CovPass app from the US app store
3. In the Settings app, configure the CovPass app to use "German" as the preferred language

![146745290-0babf5cc-18b2-422a-a1ef-7e1928a3507c](https://user-images.githubusercontent.com/11354772/150647965-b3b9a6fc-48f3-47e2-b3dd-b57496de9df3.png)

4. Open the CovPass app. Notice that the date of the certificate is shown in **Month/Day/Year** format (the default for US english) instead of the expected **Day.Month.Year** format. Navigate through the configured/added certificates. Each page showing a date/time will show this error. See the uploaded images below.

![20220122_162813000_iOS](https://user-images.githubusercontent.com/11354772/150647997-c4f2c48a-4ca0-4904-91de-fc5ed1f2f76a.png)

![20220122_162830000_iOS](https://user-images.githubusercontent.com/11354772/150648010-e8473ff7-aba1-4968-92af-c35c4f8fa260.png)

![20220122_163041000_iOS](https://user-images.githubusercontent.com/11354772/150648021-38dcddd4-0948-4302-ad1d-998b7229ec78.png)

## Expected behaviour

Dates and times are using de-de (German) localization.

**Comment by timokoenig** [comment]
@stephanadler1 iOS separates iPhone language and region. Setting the language will not affect the region format. To use the correct format you would need to set your region to Germany in the settings under "General / Language & Region"

As an enhancement request the user should be able to set the region format for CovPass only

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
