### ISSUE TITLE
Hide favorite button with only one user

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#112]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

CovPass detail view shows a favorite button that does nothing if there is only one user.

## Suggested Enhancement

Hide the favorite button and show only if user count > 1

**Comment by Kurt57** [comment]
HI @timokoenig  its fixed and will be published with the new version.

**Comment by Kurt57** [comment]
@timokoenig should be solved with 41c9734d5e3784c5b388b234df7c42e8aa2a7f20
