### ISSUE TITLE
Add indicator to show scrollable content

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#113]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Some views like HowToScan or onboarding screens do not show an indicator for scrollable content. On smaller devices you would miss links like the data privacy or the FAQ. 

Example, below the text is a link that is not visible on small devices

<img src="https://user-images.githubusercontent.com/4365095/151062057-f46cb077-1517-4d3d-afce-8b03580215df.PNG" width="300">

Please ignore the indicator on the right because this is just me trying to show the issue without having a small device

## Expected behaviour & Possible Fix

Some indicator or a small shadow overlay that shows the user that something is scrollable

**Comment by Kurt57** [comment]
Hi @timokoenig isn´t the scroll indicator itself is an indicator for iOS users that they can scroll?

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
