### ISSUE TITLE
 Genesen-Auffrischung-Booster

### ISSUE THREAD

**Issue by mxdalchau** [Digitaler-Impfnachweis/covpass-ios#114]
Hallo,

was habe ich falsch gemacht?

Ich hatte im Dezember 2020 Corona und eine Impfung mit Biontech im Juni 2021.. hatte nun die Auffrischungsimpfung... warum ist nur ein Zertifikat gültig.. ist dort die Anzeige richtig?
![IMG_CFC1C1A3C2A3-1](https://user-images.githubusercontent.com/28609519/151240069-18b28d00-0423-40c6-8f92-114fd61df0c1.jpeg)

Mit freundlichen Grüßen

**Comment by alexcimander** [comment]
Hey @mxdalchau, 
sadly your booster 2/2 cannot be differentiated from a basic immunization which is coded as 2/2 as well. Knowing that the app recognizes your booster as basic immunization. In those cases the app currently seems to fail with sorting the certs based on the "date of vaccination". That is an enhancement/bugfix that we now put in our backlog.

However, when it comes to your certificate I would kindly ask you to be patient for a few more days. The issue with the unrecognizable boosters you are facing is a common issue within germany. We are currently working on a german-wide solution for it (boosters after vaccine after recovery should be coded as 2/1). 

Thank you for your request and active feedback! 👍

**Comment by Kurt57** [comment]
@mxdalchau hi,

is this problem still present ?

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
