### ISSUE TITLE
iOS 15.4 Health integration

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#116]
The first beta of iOS 15.4 was released today. It includes infrastructure to integrate the EUDCC codes with the Health app and from there share them to wallet (which makes it quite easy to access too). With the beta installed when scanning a QR code with the built-in camera app or QR code scanner it will import it to the health app.

CovPass should integrate with the health app and provide records to the app and also retrieve records from the app if they are not in CovPass already. There should be HealthKit APIs for that.

**Comment by timokoenig** [comment]
ref https://github.com/Digitaler-Impfnachweis/certification-apis/issues/9

**Comment by Kamik423** [comment]
Ah, oops; it is kind of hard to keep track of all the separate repositories. Thanks.

**Comment by timokoenig** [comment]
@Kamik423 no worries, same for me
