### ISSUE TITLE
Johnson&Johnson certificate 2/1

### ISSUE THREAD

**Issue by croco9608** [Digitaler-Impfnachweis/covpass-ios#117]
Hello

I would like to travel to Germany.
I live in Belgium and have been vaccinated with J&J twice. My second certificate is labeled as 2/1. It is considered as a booster jab in Belgium. However not anymore in Germany.

I’ve read on the developers page of Covpass that the 2/1 will now be recognised as a booster vaccin for those who have been infected with Covid since the latest update of the covpass app. However i have never been recovered from covid so how will that effect when my certificate gets scanned?

Will my certificate be valid in Germany and if yes for how long? my second dose was from november 26th

**Comment by Ein-Tim** [comment]
AFAIK a second vaccination after a vaccination with J&J does not count as a booster anymore. 

However, I have to admit that I los track because many federal states have different regulations.

You should try to find the information on the websites from the federal states you plan to travel to.
