### ISSUE TITLE
Add swipe-to-delete function

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#118]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently a certificate can't be deleted by tapping on the person, scrolling down and then swiping the certificate away (CWA supports this).

## Suggested Enhancement
Add the swipe-to-delete function to CovPass. 

## Expected Benefits
Easier delectation of certificates.

## Screenshot
To make sure everyone understand where I want to have the swipe-to-delete function, here is a screenshot from the place in the app:
<img src="https://user-images.githubusercontent.com/67682506/151446587-8a15fdfa-56d0-4bbb-ad82-d563d91bd0ff.jpeg" width="300">

**Comment by timokoenig** [comment]
That is a nice-to-have feature but how often does a user deletes certificates?

**Comment by Ein-Tim** [comment]
@timokoenig If e.g. test certificates are stored in the app users will quite often delete certificates, for vaccination/recovery certificates you are right these are probably not deleted that often. 

As you say, would be nice to have to better integrate into the OS.

**Comment by timokoenig** [comment]
@Ein-Tim yes, makes sense for test certificates.

Instead of deleting certificates to keep it organized I would rather see an archive feature where test certificates get automatically moved as soon as they are not valid anymore. So you can still keep track of your past tests. Sometimes you might want to check when you had your last test taken

**Comment by alexcimander** [comment]
Hey everyone,
as @timokoenig mentioned a swipe to delete- or an archive-feature would definitely bring some value if we would have more certificates within the apps that are short term valid. However, test certificates are still rare within the CovPass. 

If more test-certificates will find its way into the app your enhancements will be taken into account 👍 

thank you once more for your active feedback!

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
