### ISSUE TITLE
Add Certificate to Wallet (feature request)

### ISSUE THREAD

**Issue by Felix-Pi** [Digitaler-Impfnachweis/covpass-ios#12]
Adding the certificate to wallet could not only improve the access speed, the certificate could be automatically opened in certain areas.

**Comment by Ein-Tim** [comment]
Same as https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/37.

**Comment by nappy** [comment]
I am torn on this. Yes it might not be a good idea to have the personal information accessible unlocked, but on the other hand by having to unlock the phone to show it to strangers you could potentially leak a lot more information.
I think in the end of the day, it is an trade-off, the user has to judge on himself and I think this feature should be implemented.

**Comment by sroettgermann** [comment]
Since there is an option to restrict the access to the wallet on the lock screen via FaceID or TouchID (at least via PIN code) I see no problem in having the QR Code in the wallet. 
You have to give access to the wallet actively - otherwise you're not able to access the device.

**Comment by jleufgen** [comment]
Hi all, there are currently no plans to transfer the QR code to Apple Wallet. Therefore, I will close the ticket.

**Comment by JWThewes** [comment]
Any explanation would be great. This would be a real useful feature. I think it might be better to provide a native integration instead of people using *some* 3rd Party service...

**Comment by mludi** [comment]
But having a dark mode, wow 🙄

**Comment by sroettgermann** [comment]
An explanation would be really nice. It makes no sense to me as well.

**Comment by msifrt** [comment]
Apple actually released an Update on this:
https://support.apple.com/guide/iphone/iph7f2865325/ios

**Comment by Ein-Tim** [comment]
@msifrt 

This does not help here, as Apple only supports this for certificates which are based on the SMART health card system.
