### ISSUE TITLE
How is the federal state determined‽

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#122]
I know it is not tracking my location. Is it using the IP address? Or just not making any assumption about a state and what it is trying to tell me is that it is gonna be inaccurate in most states? This message needs to be clarified!

![6C7ABC74-D55E-4338-8855-DBFC3E928508](https://user-images.githubusercontent.com/16278233/152154246-f13a7fde-3bbc-461a-bbc5-4247a443bb67.jpeg)

**Comment by Ein-Tim** [comment]
> Which rule applies depends on the federal state you are in.

Only means that you should check whether 2G+ or 3G is the correct checking mode. There is no determination of the state.

**Comment by Kamik423** [comment]
The way the note is formatted looks like it is specifically talking about 3G, not checks in general. Also some rules might not be closed by the state but instead an event organizer such as constraining something to 2G only, or necessarily requiring a test. This makes this message doubly confusing.

And does this also mean the app is incapable of checking for variant rules of the federal states?

**Comment by Ein-Tim** [comment]
> The way the note is formatted looks like it is specifically talking about 3G, not checks in general.

Very true. 

> And does this also mean the app is incapable of checking for variant rules of the federal states?

Yes, there is no selection of different states or similar. The controlling person has to make sure that everything is correct for their federal state, in the very end.

**Comment by Kamik423** [comment]
> The controlling person has to make sure that everything is correct for their federal state, in the very end.

Well what is the point of using the app then in the first place? 

Currently it missing booster checks and even when they are gonna be implemented they will be invalid for most states due to J&J.

**Comment by Ein-Tim** [comment]
> Currently it missing booster checks and even when they are gonna be implemented they will be invalid for most states due to J&J.

What do you mean?

**Comment by Kamik423** [comment]
Currently the app is going to be useless for confirming 2G+ (With booster replacing test). Most people are boostered now and multiple states have this rule.

Even if the app now implements booster checking but no rule variance for states it is still gonna be useless in all the states that vary from the national rule by requiring a 3rd vaccination with J&J.

**Comment by timokoenig** [comment]
@Kamik423 the J&J problem can be fixed without an app update. The rules on the national backend just need to be updated

**Comment by Kamik423** [comment]
To my understanding every state has different rules for how valid J&J first booster is (2/1). Will the App every be able to account for variations like this? How does it detect the state? And what does the national backend have to do with it?

https://www.merkur.de/welt/johnson-booster-impfung-corona-regeln-bayern-nrw-bawue-sachsen-berlin-news-zr-91242821.html

**Comment by Dale81** [comment]
@Kamik423 guess the state-based rules will not be reflected as they are so complex. Also the app would need a selection for the Bundesland to know, whick rules to use. But currently even the J&J one-dose vaccination is still not used during validation of the certificate even this is possible. So this also needs to be fixed to have a fully usable app again as currently NO 3G/2G/2G+ validation can be trusted by using this app because the certificate could always be J&J one-dose.

**Comment by Kamik423** [comment]
![CC43FE22-1DFA-4ABD-87C3-87FF3CA8EA35](https://user-images.githubusercontent.com/16278233/154595406-b3265c1d-6894-4521-a6fe-535e67c07c97.jpeg)

Mai this is the latest updated. Does this mean it is automatically determining the state or does it tell me to apply rules manually?

**Comment by timokoenig** [comment]
The app only differentiates between country and domestic. The app expects all states to have the same rules

**Comment by Kamik423** [comment]
Why is the sentence

> Which rule applies depends on the federal state you are in.

Even there then? What is it trying to say if all states are the same?

**Comment by timokoenig** [comment]
I guess only the team can answer that question. I would've expected something different as well

**Comment by Ein-Tim** [comment]
@Dale81 In CovPass you can select other countries to check whether you are eligible for traveling into this country. In CovPassCheck you can select whether the rules inside of Germany (domestic) or for entering Germany (country) should be used.

**Comment by Ein-Tim** [comment]
Can this issue be closed?
