### ISSUE TITLE
"2G+" mode: Not obvious how to scan the second certificate

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-ios#124]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
I just had my first experience with the new "2G+" mode in CovPassCheck, and as I currently by chance have a pair of vaccination and test certificates for the same user around, wanted to try it out. 

I successfully scanned the vaccination certificate, got this screen:

![image](https://user-images.githubusercontent.com/5329491/152165180-1ba0f250-14d9-4609-9a71-e9d04a012423.png)

and then was stuck. 

What should I do now?

I clicked on the "button" with label "Testzertifikat - Noch nicht geprüft", but nothing happened.
I went back with the "X" in the hope that I then can scan the test certificate, but no, then I got the same screen this time with missing vaccination certificate. 

It took me a while to find out how to do it: 

You have to SCROLL down, there you find the buttons "Scan test certificate" and "New check"...

## Suggested Enhancement
Either put the "Scan (now) the ..." buttons on top, or let the "Missing ..." button trigger the scan, or use scroll-bars to indicate the page is not yet finished.

## Expected Benefits
I assume myself to be tech-savvy, but I nearly failed. This might indicate that regular users fail more often.

**Comment by Ein-Tim** [comment]
This feature was obviously designed for iPhones with a big screen:

| iPhone 6s | iPhone XR |
|---|---|
| ![iPhone 6s](https://user-images.githubusercontent.com/67682506/152172720-4ab8363c-e41a-4fbd-8bd8-08f810f5e0c6.jpeg) | ![iPhone XR](https://user-images.githubusercontent.com/67682506/152172795-e40fc3fe-76bf-4980-bf2d-e45efccd011f.jpeg) |

**Comment by timokoenig** [comment]
Seems relatable to my issue that I created a couple days ago https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/113

**Comment by timokoenig** [comment]
IMO the usability for the second scan can be vastly improved. In case of an invalid test certificate I have to click three times to scan it again because the reason for the error is not displayed directly on the screen

**Comment by RobTho** [comment]
Maybe the upper "Testzertifikat" could be used (by tap on it) for scanning when "noch nicht geprüft"
So the lower "Testzertifikat" Button would be not needed anymore

**Comment by boecko** [comment]
Additionaly:
When you scan an invalid/random QR-Code  **FIRST** in 2g+ mode you'll get the invalid qrcode error.
A press on "Neue Prüfung" fallbacks to 3G mode scan.

How this behavior didn't show up the QA Tests is beyond me.

**Comment by Staeffy** [comment]
Closing as this screen does not exist anymore
