### ISSUE TITLE
Apple Wallet support 

### ISSUE THREAD

**Issue by iMonZ** [Digitaler-Impfnachweis/covpass-ios#126]
Since there is no discussion option in this repo I opened an issue instead.

Is there a plan of implementing the Apple wallet feature so you can export the QR code and use it on the Apple Watch and iPhone?

https://developer.apple.com/wallet/

It should be possible from the technical view and it would be a great and fast accessible feature

**Comment by Ein-Tim** [comment]
iOS 15.4 is now released to the public. I think it would make sense to investigate whether it is possible to add a "Add to Wallet" button to CovPass. 

cc @Kurt57

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
