### ISSUE TITLE
CovPassCheck App(V 1.17(1) is not able to verify 2/1 certificates

### ISSUE THREAD

**Issue by Stevildo** [Digitaler-Impfnachweis/covpass-ios#128]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone
- OS version: 15.2.1
- App version: 17.1

## Describe the bug

The EU decided that booster vaccinations should be certified as 2/1 starting from 01.02.2022 instead of, how it's handled currently, 2/2.

See https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837 which says:

"In addition, today the Commission has also adapted the rules for the encoding of vaccination certificates. This is necessary to ensure that vaccination certificates showing completion of the primary series can always be distinguished from vaccination certificates issued following a booster dose.

Boosters will be recorded as follows:

3/3 for a booster dose following a primary 2-dose vaccination series.
2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person."
CovPass should be adapted so that it works properly with those certificates (i.e. not show "Impfung 2 von 1", the validity check for Germany needs to be adjusted, etc.).

CovPass App (V 1.17(1)) shows valid certificate with 2/1
**but CovPassCheck App(V 1.17(1)) is not able to verify it.**

Please fix it - thank you!

## Steps to reproduce the issue

scan 2/1 certificate with CovPassCheck app

**Comment by Ein-Tim** [comment]
@Stevildo 

Could you try whether updating the rules makes a difference. 
Click on the "?"-icon in the top right corner, click on "Prüfregeln aktualisieren" and then on "Aktualisieren".

Does this change anything?

**Comment by Stevildo** [comment]
@Ein-Tim 
Sorry I should have had mentioned it. Yes I updated the rules yesterday.
But today I updated again and now it is working... did you already fixed it? ;) Or is there maybe a bug in the rule update mechanism?
Thanks for your help

**Comment by Ein-Tim** [comment]
@Ein-Tim 

I'm actually only a community contributor, so don't have access to these rules (-;
Maybe the new rules which are mentioned [here](https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97#issuecomment-1032259634) are live now and fixed this issue? 

No idea. I suggest you try to reproduce this issue and if it's not possible to reproduce it, close this issue 🙂

**Comment by Stevildo** [comment]
Not reproducible anymore - I will close the issue
