### ISSUE TITLE
DCC entry check for Germany shows PCR tests as valid even though the tests are older than 48h (CovPassCheck also accepts PCR test DCCs older than 48h)

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#129]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/en/faq)
* [X] Bug affects both Android **and** iOS
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS/Android version: 15.3
- App version: 1.17

## Describe the bug

The DCC "Check travel validity" feature of the Corona-Warn-App and the CovPass-App shows PCR tests as valid for entry of Germany, although the test is older than 48h. 

This is contradictory to the information on https://www.auswaertiges-amt.de/de/quarantaene-einreise/2371468#content_2.

So, in consequence **CWA & CovPass shows certificates as valid for entering Germany, although they are not valid!**

CovPassCheck also accepts PCR tests older than 48h.

## Steps to reproduce the issue

1. Import a PCR test into the app
2. Check for it's validity to entry Germany more than 48h but not longer than 72h ago
3. See that CWA, CovPass & CovPassCheck states the certificate is valid

## Expected behaviour

The CWA, CovPass & CovPassCheck should not declare certificates as valid for entry although they are not. 

## Possible Fix

Change the validity from max. 72h to max. 48h.

## Additional context

This is related to https://github.com/corona-warn-app/cwa-documentation/issues/855.

**Comment by timokoenig** [comment]
That's nice to hear but shouldn't there be some other process to update those changes immediately after they come into effect? A bug ticket from users should not start the process after 2+ month

**Comment by Ein-Tim** [comment]
@alexcimander Will you soon fix this issue? I'm already thinking about sending a Mail to the RKI informing them about this issue, maybe they can give you a push to update the rules. Or is the RKI the show stopper here who doesn't want the app to apply with their own rules? I can't imagine this.

**Comment by Ein-Tim** [comment]
I can't believe that the RKI really is fine with this. I will write them a Mail now.

**Comment by Ein-Tim** [comment]
The RKI writes:


"Die Vorgabe, dass ein PCR-Test in der Corona-Warn-App für 72 Stunden als gültig angezeigt wird, stammt vom Bundesministerium für Gesundheit. Falls Sie dies näher hinterfragen möchten, müsste ich Sie bitten, sich zur Klärung dorthin zu wenden."

So, let's send a mail to the BMG.

**Comment by Ein-Tim** [comment]
There are no entry rules for Germany anymore, thus this issue is obsolete now, and I'm closing it.
