### ISSUE TITLE
CovPass and DGCA Verifier App use different public key lists: Which is the "correct" one?

### ISSUE THREAD

**Issue by lionwolfdev** [Digitaler-Impfnachweis/covpass-ios#13]
**EDITED 22-06-2021: I removed the CWA example from the issue description. Apparently it is supposed to be a wallet app and therefore not verifying the signature. See https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/13#issuecomment-865528242 **

***
May be related to #7 

I'm attempting to build a verifier for the health certificates by myself using a [Java implementation](https://github.com/DIGGSweden/dgc-java). I realized that CovPass is using a different public key list which does not match some of the certificate signatures (thus not accepting the certificates) that the [DGCA Verifier App](https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios) would accept with its public key list.

Example: AT Vaccination Certificate QR
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/AT/png/1.png

DE Vaccination Certificate QR
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DE/2DCode/png/1.png

cannot be verified with CovPass, but the default public key list of the DGCA Verifier App accepts it.

The second list attached below contains a lot of test environment certificates for sample health certificates, but since ~CWA and~ the DGCA-Verifier App does accept these, I'm a bit confused why CovPass doesn't.

**CovPass Certificate `kid` list from the UBIRCH API as of 21-06-2021**
```
/IcqIBnnZzc=
3IsdmTYkAAM=
4Qmniw7B0gc=
6ag2wJkSHtk=
ARrNkCRtprY=
BEnvMVnNFK8=
GMFMBu1RlCg=
GuQPQRxbMsU=
IaGR283U1jA=
JHd4CkNzadI=
MtI93IMknMk=
NCc6YSsVioM=
YRYidQ+wetg=
YU9+X9nepqU=
ZcfkloEvfGQ=
e9SH8dtWwdY=
hgpHHrTb4ws=
qFNF2dC+mjQ=
tCM87WnaaQE=
ub6Qmv9xtAo=
x3ch4ml934I=
02vdAOY/+gI=
0kAwFy+vLpg=
bBnmkeVMV6A=
ln8K+9SqfuA=
1+da8dKEjlE=
2BGoyFIyYPs=
2JelGO/ymxQ=
3LCRmucB9kU=
3jqajzfHpKE=
3lrBUHc4iQE=
3oYtiEZ9wp4=
5xtSr6KkAGA=
6FNkACSMLEc=
7XLhQx1KXdQ=
8AnF/hcilSo=
AQCGDydsS1Q=
CvktK3hdjeY=
DusseXrzqO8=
IZftFLRmKGY=
L7XIA2gi2ps=
M8bcnysCMj4=
MxhfdcoHinc=
NCdyt3s+cak=
OKpEjMo/2MY=
R7q7yd90ZPU=
TGjTR+Re+yk=
TpQIkAHAym4=
Uj77p+qIQNs=
XkVWZqUeeFc=
XuCERkHu8kY=
Yr8a8Rd+zqI=
ZDoFfkn+yhY=
bKmas9wa5tc=
dhSzPDr4G2M=
i5SVuCsR5TA=
izUDZjGtHWY=
juskqrNQf6k=
kjEx2H7huNE=
nPKEYm3gXzU=
nTrG8glLUls=
npo0ZWgdQSY=
r9YkEJZgi9k=
sYXcYixrOGA=
vjm0I2ATJ+Y=
yWCRdph8XJs=
25QCxBrBJvA=
AN1EeLIMAmo=
FDNJjaSCWi0=
HhkeqvrtQ0U=
EzYR1uk/E0I=
Is2JtrOJhik=
Jjql9rBrjHI=
NAyCKly+hCg=
NJpCsMLQco4=
ODqaG8mnbro=
Pbydc1LscXo=
e4lH6I4iMIM=
fNf883wPIEg=
hFpY/ySOrwI=
lshLbYfCWRg=
vvYa1vaWkGg=
```

**DGCA Verifier App `kid` list from the SAP API as of 21-06-2021**
```
IAPAel6V04Y=
OTDtSL6sHfA=
nAj5VPXn/t4=
6EjzyhNlGDQ=
RCLmunqODLU=
jd4FUVxAJjY=
TfwLMHDXIws=
jrN5lgS8Vjo=
y3g27v8r51I=
0+tvAJnJsPQ=
v58a8hf49kE=
KFP4Rwxlab8=
yLHLNvSl428=
0C6apRBXqu8=
DEsVUSvpFAE=
2pwTzcIIZUo=
k9Bla6IJw9M=
ejprUkT1iiw=
X3SRAZXFzss=
OTAXaM3aBRM=
TdAfEdSpTWg=
dZl5Qc0tmyE=
MAOnQ1AiTeM=
2Rk3X8HntrI=
mkooSvJQkZ0=
428FOlUxNRM=
t4pdJoYfDjY=
xAE9ugovQD4=
sLgjDFuTktM=
wDOFD1gh/so=
1vxpTLgc6ws=
kwL2uX0ViAA=
ri1AFZuP96k=
0NSBDWlaTng=
6jqyJk80bUU=
U59MpT2oM1M=
Yd1kEA/PdIs=
7JQ83GRvK3A=
BWANBUcVq6M=
f1sfUVIx8CA=
p2yABmeC8Bg=
drYeMLDIJ08=
110WCQIlRgY=
SnQA8f0kXUs=
Jvur7gP5KB8=
2Ga7nn3++CU=
Pl2tK5b5Ubs=
NSbroRZKHVQ=
GZ2cfMLwyK8=
qXRLozKN0lM=
xKOXcpzMVb0=
q16CfHxK02k=
d1ZunoZIq1g=
onphe00laog=
uTWhkSj2GAo=
Sr45aGku6g4=
BkMNTz/RKb8=
mmrfzpMU6xc=
DhspllZjSVY=
m6so0I2uIyw=
MZmKdKXodNA=
pgM4dDtABSg=
```

**Comment by Ein-Tim** [comment]
Reg. CWA, please note that CWA is able to scan & store certificates without a valid signature: https://github.com/corona-warn-app/cwa-documentation/issues/634

**Comment by lionwolfdev** [comment]
Thank you for your clarification, this helped me a lot to understand why the apps handle the codes so differently. I removed the CWA example from above.

This might also answer the question inside the issue's title. The API URL listed at the DGCA Verifier App repository is probably for testing purposes only and CWA accepting the QRs was just a coincidence (as it does not verify the signatures). Because two other apps accepted the codes while CovPass did not, I falsely concluded that CovPass might be using an incomplete certificate list.

I therefore assume it is intentional that CovPass does not accept the QRs listed above, as they are signed with invalid test certificates? If this is the case, this issue can be closed.

**Comment by timokoenig** [comment]
@lionwolfdev do you still need help?

The QR codes from above work fine if you use the correct public keys for the test environment
