### ISSUE TITLE
Domestic and Entry Rules are wrong

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#131]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Domestic rules do not reflect the current valid rules within Germany.

* Antigen is valid for 24
* PCR is valid for 48
* Full Immunization has no expiration date
* Nu­va­xo­vid is also an allowed vaccine

## Expected behaviour

Domestic rules are correct so that CovPassCheck can be used within Germany.

**Comment by alexcimander** [comment]
Hey Timo,

a new version of domestic rules is live! I will from now on report current rule sets using the announcements.

Thank you!

**Comment by timokoenig** [comment]
@alexcimander just looked at the "updated" rules and they are still wrong and do not reflect the current state of the domestic rules.

**Comment by Ein-Tim** [comment]
@timokoenig Do you have a quick links to the domestic rules for me? On https://timokoenig.github.io/eu-dcc-rules/?country=DE&rule=RR-DE-0001 there are only the entry rules, or?

**Comment by timokoenig** [comment]
@Ein-Tim yes on that page are only the EU entry rules.

I had a look at the API that provides the domestic rules: https://distribution.dcc-rules.de/domesticrules

**Comment by Ein-Tim** [comment]
Thank you so much @timokoenig!

**Comment by timokoenig** [comment]
Just noticed that even the entry rules for Germany are wrong.

PCR tests are only valid for 48 hours but CovPassCheck allows 72 hours

In case the information are missing, you can find it on the BMG website: https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Einreiseregeln_CoronaEinreiseV_Kurzuebersicht.pdf

**Comment by Ein-Tim** [comment]
See also https://github.com/corona-warn-app/cwa-documentation/issues/819.

**Comment by timokoenig** [comment]
Another week passes and the rules are still wrong

**Comment by timokoenig** [comment]
related to https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/131

**Comment by timokoenig** [comment]
related to https://github.com/Digitaler-Impfnachweis/covpass-android/issues/189

**Comment by timokoenig** [comment]
ignoring the problem doesn't make it go away 🙃

**Comment by Ein-Tim** [comment]
Will someone address this issue anytime soon? Is the RKI ok with its apps being out of touch with reality?

**Comment by timokoenig** [comment]
I guess ignoring the issue made it go away because now the rules are gone 😄
