### ISSUE TITLE
Misspelling in AppStore Update text

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#134]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The update text on the AppStore has a word too much `...Außerdem können Sie können...`

> Mit diesem Update stehen Ihnen neben Fehlerbehebungen auch neue und erweiterte Funktionen zur Verfügung. Außerdem können Sie können nun die Gültigkeit Ihrer Zertifikate im Kontext einer Reise durch Europa und weitere Staaten oder innerhalb von Deutschland prüfen.

## Steps to reproduce the issue

1. Go to the AppStore

**Comment by Kurt57** [comment]
@timokoenig 

I think it's because CovPassCheck was filed as 1.18.0 in the AppStore instead of 1.18

**Comment by timokoenig** [comment]
@Kurt57 where is the connection between the version and the AppStore text?

**Comment by Kurt57** [comment]
@timokoenig for CovPass the Apple API retrieving 1.18 for CovPass Check its retrieving 1.18.0.
The App build is 1.18 for both apps.

**Comment by timokoenig** [comment]
@Kurt57 I think you are talking about https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/136 and not this ticket

**Comment by Kurt57** [comment]
Oh,yes. Sorry.

**Comment by alexcimander** [comment]
hey everyone!

Can't be fixed afterwards but a new version with new release notes will be out soon!
