### ISSUE TITLE
There is no 2G option

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#135]
There currently is no option to scan 2G certificates. 2G is however sometimes applicable and needs to be checkable. For example I got an email from my Uni today:

> 2G holds for visitors to
scientific events such as conferences and congresses.

Not providing this feature is a critical failure since it negates all the privacy and speed benefits of the EUDCC as they will have to take your phone, scroll through your certificates and visually confirm it is not a test while not actually scanning the code.

**Comment by timokoenig** [comment]
The 2G+ mode can be used for that. After the scan it will show you if the scanned certificate is a vaccination or recovery and if it's valid

**Comment by Kamik423** [comment]
Isn’t that also very much not the point of the app? Why not just add a 3rd mode and hide the type?
