### ISSUE TITLE
Update dialog even though newest version is installed

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#136]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The update dialog appeared after opening the app even though the newest version is installed.

## Steps to reproduce the issue

1. Download newest version
2. Wait a day
3. Open the app

## Expected behaviour

The dialog should not appear when the newest version is installed

## Possible Fix

Can't check because source code is not available yet

## Additional Information
<img src="https://user-images.githubusercontent.com/4365095/154669551-f1667b0e-0295-417f-9b16-bdd2ee0591cd.PNG" width="300" />

**Comment by timokoenig** [comment]
> @timokoenig for CovPass the Apple API retrieving 1.18 for CovPass Check its retrieving 1.18.0. The App build is 1.18 for both apps.

This seems possible. So it's either trust the person that publishes the app or make the app more resilient, for example by adding the patch version if it's not set

**Comment by Ein-Tim** [comment]
@Kurt57 

I guess this means this issue will fix itself with the next update?

**Comment by Kurt57** [comment]
@timokoenig 👍 

@Ein-Tim yes 💯

**Comment by Kurt57** [comment]
@timokoenig this is solved?
