### ISSUE TITLE
Fix corner radius on app icon

### ISSUE THREAD

**Issue by janekwunderlich** [Digitaler-Impfnachweis/covpass-ios#14]

**Comment by timokoenig** [comment]
@janekwunderlich do you mean in the Github README?

**Comment by janekwunderlich** [comment]
I mean yes, that is the same asset but it's causing the corner in iOS as seen in the video attached. According to Apple Design Guidelines the app icon aaset has to be square with no rounded corners, otherwise it results in artifacts. https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/  https://user-images.githubusercontent.com/41242501/123082243-1a955100-d41f-11eb-8757-006dbe36be4a.MOV

**Comment by janekwunderlich** [comment]
To resolve this issue the app icon needs to be re-exported in a square shape and replace the assets in https://github.com/Digitaler-Impfnachweis/covpass-ios/tree/main/Source/CovPassApp/Source/Resources/Assets.xcassets/AppIcon.appiconset

**Comment by timokoenig** [comment]
Fixed with version 1.4.1
