### ISSUE TITLE
CovPass and CovPassCheck handle recovery certificates differently

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#143]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Because of the recent rule changes for recovery certificates, the CovPassCheck declines certificates that are older than 90 days. CovPass on the other hand shows recovery certificates valid for 180 days. This definitely confuses people at the CheckIn.

## Expected behaviour

CovPass and CovPassCheck should show the same validity period for recovery certificates

## Possible Fix

Do not use the fix validity date from the recovery certificate and replace it with a static value from the rules.

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/1f1f5d283dfccc87efb8dadf8723c5f18721e449/Source/CovPassCommon/Sources/CovPassCommon/Models/Recovery.swift#L29

## Additional context

This bug applies to Android and iOS.

**Comment by alexcimander** [comment]
Hi Timo,

both apps check for the same travel- or domestic rules. Can you clarify what is meant by your ticket? Are you saying that recovery certificates can be "scanned" for 180 days? Or are you saying that we are still have 180 days displayed within the certificate details in the attribute "höchstens gültig bis?"

**Comment by timokoenig** [comment]
@alexcimander the recovery certificate is shown valid in CovPass even though CovPassChecks will decline it. This confuses people because they think they have a valid certificate but in reality they don't. Then it comes to discussions at the entrance of restaurants etc.

**Comment by timokoenig** [comment]
More and more people complain about the differences. IMO this should be fixed soon

**Comment by aherberger** [comment]
Just some marketing: If you want an App which can check the rules correctly look for our (free) App https://www.digitalkeycheck.com - this can handle (mostly) all special situtations and doesnt leave the decision to the user.
It also contains an (optional) ID-Card validation.

**Comment by alexcimander** [comment]
Hey everyone,

so if I understood it correctly it is about what the detail-screen of the certificate is "suggesting" but not about different results when it comes to rule-checks. 

We are currently investigating solutions. Just using the rules as reference might be misleading as well since within the EU your certificate is still valid. 

There are running discussions about how to display it properly - I will keep you updated

**Comment by timokoenig** [comment]
It's not only about the detail screen but also the QR code that shows on the card. CovPass suggests that this is a valid QR code but CovPass Check will fail to scan it

**Comment by Ein-Tim** [comment]
This issue is technically solved because CovPass "Maximum valid until dd.mm.yyyy". I suggested to change the wording via https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/180.

**Comment by Ein-Tim** [comment]
FYI: According to https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.40.0 this has been fixed.
