### ISSUE TITLE
Show rule count for "Check Validity for Travel" feature

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#144]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

The country list in the "Check Validity for Travel" feature does show all available countries even though they do not have any rules.

## Suggested Enhancement

If you show all countries (which is not good in my opinion) you should at least have some sort of hint or the actual rule count next to the country before the user selects it. Users complain that none of the countries they select work. In those cases the selected country does not have any EU entry rules.

## Expected Benefits

The users will know that the country they try to check is not valid because they do not have any entry rules, meaning less people will complain about this 😄

**Comment by timokoenig** [comment]
@alexcimander I know, but I still don't like it 😄 anyways...

I can prepare you a PR is you want. You only have to say if you want `x rules available` behind every country with rules or just mark every country without rules with `No rules available`

**Comment by Kurt57** [comment]
check validity feature is not available anymore.
