### ISSUE TITLE
Do not show hint for Germany when selecting another country

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#145]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When the user selects another country in the "Check Validity for Travel" feature, they get a hint for Germany that does not make sense.

<img src="https://user-images.githubusercontent.com/4365095/156023595-e30ccf21-18f6-4d80-8c03-2c692d7527f7.jpeg" width="300" />

## Steps to reproduce the issue

1. Open "Check Validity for Travel"
2. Select France3. 
3. See that there is a hint for Germany

## Expected behaviour

The hint should only be visible when the user selects Germany (country / domestic)

**Comment by Kurt57** [comment]
This is already fixed in the prepared version. @timokoenig

**Comment by Kurt57** [comment]
@timokoenig can be closed?

**Comment by timokoenig** [comment]
It's not fixed yet
