### ISSUE TITLE
Spelling mistake on "What's New" dialog

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#152]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- App version: 1.19

## Describe the bug

Spelling mistake in the second title of the "What's new" dialog -> `assignmen`

<img src="https://user-images.githubusercontent.com/4365095/156376798-d5e6908f-9bf7-4c0c-9abe-4a7494be0f26.PNG" width="300" />

**Comment by Kurt57** [comment]
@timokoenig can be closed?

**Comment by timokoenig** [comment]
your call, since this won't get fixed
