### ISSUE TITLE
Wrong birthdate date format

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#153]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- App version: 1.19

## Describe the bug

The birthdate date format `01 Jan 1970` does not match the given format `YYYY-MM-DD`

## Steps to reproduce the issue

1. Open "Check Validity"
2. Click on certificate
3. Birthdate format does not match the format that is given in the title

## Expected behaviour

Birthdate should match the format given in the title

**Comment by alexcimander** [comment]
Thank you Timo for reporting this bug - we created a ticket for it. We give you an update asap

**Comment by Kurt57** [comment]
Hey @timokoenig  should be resolved. Can you confirm and close?
