### ISSUE TITLE
Option to deactivate "New Features" screen

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#155]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently after a (non patch) update, users are always welcomed with a "New Features" screen.

## Suggested Enhancement
Make it possible to deactivate the showing of this screen in the settings of the app.

## Expected Benefits
There are many users complaining about this screen on Twitter (e.g. [here](https://twitter.com/ZSleyer/status/1495346255345725444?s=20&t=g0C9VkQV2UGjWQ8c1BUHnw)). These users are stating that they are not interested in the new features of the app and it just slows down their usage of the app to present their EU DCC.
These users will probably not read through the text on the screen but just click on the button to dismiss the screen. Thus, giving an option to deactivate this screen, won't make the users less informed about the new features in the app.
Showing a splash screen, which hinders users from using the app as normal until dismissed, is quite an an _aggressive_ way to inform about new features.
Thus I think that there should be an option to deactivate the showing of this screen in the settings.

**Comment by Ein-Tim** [comment]
Related issue: 

- #186

**Comment by timokoenig** [comment]
I just proposed a different idea to show the announcements: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/186#issuecomment-1064389418

**Comment by Kurt57** [comment]
Hi @Ein-Tim 

i have created a ticket in our internal tracking system.

Thank you!

Regards,
Fatih

**Comment by Ein-Tim** [comment]
- Seems like this will soon be possible: https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/236

**Comment by Ein-Tim** [comment]
This has been implemented.
