### ISSUE TITLE
The git history is a mess 💩 

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#157]
The current git history is a complete mess which makes it really hard to run compares on it.

- There are some commits twice on the same branch?!
- A cherrypick of a release on a master and then the release gets merged? That could be one of the reasons why the history is so messed up
- Commits like `fix`, `Cherrypick/master`, `BVC-3624` as a commit subject is not very descriptive

I'm not sure what changed the last two releases but maybe consider a better workflow or apply other git best practices. Other developers and I would appreciate a short explanation of the current development workflow and branching strategy in the README

**Comment by timokoenig** [comment]
The whole project doesn't build anymore because of duplicates that might be caused by previous conflicts. Please fix asap

<img width="935" alt="Screen Shot 2022-03-04 at 19 09 05" src="https://user-images.githubusercontent.com/4365095/156818333-cfbebe8a-2f79-4575-8049-ccdc6b56951e.png">

**Comment by Kurt57** [comment]
Thank you @timokoenig can you recheck this build issue. There is a new commit.

**Comment by timokoenig** [comment]
Thanks, build issue is gone but unit tests do not run without problems.

**CovPassCommon**
```
covpass-ios/Source/CovPassCommon/Tests/CovPassCommonTests/CertLogic/DCCCertLogicTests.swift:140: error: -[CovPassCommonTests.DCCCertLogicTests testValidVaccination] : XCTAssertEqual failed: ("1") is not equal to ("0")
```

**CovPass**
10+ tests fail because of missing reference images. They don't seem to be included in the repository

**Comment by Kurt57** [comment]
Sometimes it comes to the test certificates in the tests expire. Then these will of course be updated with the next repo update.

Can you post a list of which tests Reference images are missing?

**Comment by timokoenig** [comment]
I think the easiest is to set a fixed date in the tests so that the static certificates do not expire. That could make things a bit easier.

Regarding the tests see the following screenshots where it fails. Also note that the last SnapShotTest didn't even run. Is there a reason why this is disabled?

<img width="412" alt="Screen Shot 2022-03-05 at 00 27 35" src="https://user-images.githubusercontent.com/4365095/156855800-f3d9b383-d43c-47a6-9d9d-24d45c437355.png">

**Comment by Kurt57** [comment]
Can you please try running snapshot tests on iPhone 11 (14.3)

The last one has to be realigned. Some of that test will be removed (because vc will also be removed -> unused)

**Comment by timokoenig** [comment]
That's something that should be mentioned in the Readme. Besides that there are still tests that fail. Here is an example where I think that the reference image is just wrong. The button at the bottom should have two lines but has only one in the reference image, therefore the word 'smartphone' is missing.

Reference:
<img width="214" src="https://user-images.githubusercontent.com/4365095/156860676-f07787fa-da2e-47e6-a3e5-5d1975382ae7.png">


Failed Test:
<img width="214" src="https://user-images.githubusercontent.com/4365095/156860681-00cdc490-0ee1-492c-b977-00e717456e2a.png">

**Comment by timokoenig** [comment]
I will check that this does not happen anymore with the upcoming releases.
