### ISSUE TITLE
Do not show "Negativer Test von vor 0 Stunden" but "Negativer Test von vor unter einer Stunde"

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#159]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The app shows "Negativer Test von vor 0 Stunden" if a test is scanned which was taken less than a hour ago.

## Suggested Enhancement
Show "Negativer Test von vor unter einer Stunde" instead of "Negativer Test von vor 0 Stunden".
Alternatively, you can also completely remove the time from the title, as the exact time stamp is shown below.

## Expected Benefits
Humans do not say that something was "vor 0 Stunden" if something happened less than one hour ago. As the app is intended to be used by humans, it makes sense to communicate as they would expect. 😉

## Screenshot

<img src="https://user-images.githubusercontent.com/67682506/157686351-caf1cfd4-b2f0-4de2-8fef-89205b4ade8d.PNG" width="300">

**Comment by Kurt57** [comment]
Hi @Ein-Tim 

i have created a ticket for this in our internal tracking system.

Thank you a lot for this enhancement.

Regards,
Fatih

**Comment by Ein-Tim** [comment]
@Kurt57 Has the text been adjusted in the meantime?

**Comment by Kurt57** [comment]
Hi @Ein-Tim not yet but hopefully soon. We are working hard on some new features. Afterwards hopefully the bug will find its way to one of the next sprints.

**Comment by Staeffy** [comment]
closing this, as we don't have the screen anymore
