### ISSUE TITLE
UX improvements for devices with small screens

### ISSUE THREAD

**Issue by FlightMS** [Digitaler-Impfnachweis/covpass-ios#16]
I've installed CovPass on a iPhone 6s.
If I want to see my certificates, I have to scroll inside the box first. I think, this should be optimised.

![CovPassScroll](https://user-images.githubusercontent.com/82420268/123112204-d1a0c500-d43d-11eb-999a-c00c374a4848.jpg)

**Comment by kNsja5w** [comment]
Is there an update on when this fix will be released in the official app on the AppStore?

Thank you!

**Comment by timokoenig** [comment]
This topic is still with the UI/UX designers, therefore still work in progress.

I agree that this should be optimised but as far as I can see It on your screenshot it does not affect the scanning. Also you can click anywhere on the card to see your certificates and don't need to scroll to the "Zertifikate anzeigen" text.

**Comment by timokoenig** [comment]
Margins and other adjustments for smaller devices have been made with version 1.4.1
