### ISSUE TITLE
EU Rule Download hash matching does not work

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#164]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- App version: 1.19

## Describe the bug

The app has a build in hash matching that should prevent downloading rules twice. For some reason this matching does not work anymore. Meaning every time the EU rules get updated, the app download **ALL** rules instead of only the new rules.

## Expected behaviour

Only new rules should be updated on the device to reduce network traffic.

**Comment by Kurt57** [comment]
Hi @timokoenig ,

Thank you for your message.
I will create a ticket to track this in our backlog.

Many kind regards!
Fatih

**Comment by Kurt57** [comment]
@timokoenig can you maybe explain bit more detailed the steps to reproduce?
unfortunately I cannot reproduce this.

**Comment by Kurt57** [comment]
Ok I can reproduce this but not sure why this is happening. I'll go deeper now and let you know as soon as I figure something out.

**Comment by timokoenig** [comment]
@Kurt57 I haven't checked the cause but maybe the app doesn't save the hash therefore it can't compare it with the next update

**Comment by Kurt57** [comment]
Yes seems like since some or all (checking and clarifying atm) detail response of a rule doesn't provide its  hash (anymore ?)

**Comment by Kurt57** [comment]
Seems like that the part you are describing is not anymore available. 

https://github.com/Digitaler-Impfnachweis/covpass-ios/commit/9c733d193aecc4857d0b8765de7b631109e9715d

**Comment by Kurt57** [comment]
It's fixed and will come with the next version @timokoenig

**Comment by timokoenig** [comment]
@Kurt57 great thanks!

**Comment by Kurt57** [comment]
@timokoenig can you confirm the fix? See the reference
