### ISSUE TITLE
Aggregate EU rules in one JSON file

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#165]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

The app downloads all EU rules individually. Sometimes the EU rules API does respond with an error when there are too many open connections. This causes the rule download to fail and the app is left with the old rule set until the next try.

## Suggested Enhancement

Aggregate the EU rules on a separate server and let the app download that one JSON file. This is faster and reduces the traffic for the device.

**Comment by Kurt57** [comment]
Hi @timokoenig ,

Thank you for your message.
I´m not really sure this is a iOS App enhancement.

So the API we are consuming is provided and not maintained by iOS-CovPass Team. 
If there is a solution for aggregated eu rules in one JSON file, than it can be done.

Many kind regards!
Fatih

**Comment by timokoenig** [comment]
Even if the team is unwilling to build an aggregation, the app should improve the error handling that catches and retries failed requests

**Comment by Kurt57** [comment]
Definitely there is room for improvement there. As in many places in the app, and at all times. 

Let me check out if and how we can claim an aggregated JSON so the app can consume it.

Also, we will still have to weigh if this proposed way really fixes our problems. After all, the current implementation also comes with benefits that we'll have to weigh once.

**Comment by alexcimander** [comment]
Hey Timo,

we will definetly raise this point. There are also other improvements we have in mind. We are in multiple discussions right now to improve request handling etc. we will keep you updated.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
