### ISSUE TITLE
First favorite certificate only works with vaccination certificates

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#166]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When the user scans the first certificate, we mark this certificate as his favorite. This currently only works with vaccination certificates. If the user scans a test or recovery certificate, it will not get marked as favorite.

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/132851b053e0ad9fba15bb9b2a2fc76fbffbeb95/Source/CovPassCommon/Sources/CovPassCommon/Repository/VaccinationRepository.swift#L294

## Expected behaviour

The certificate type should not matter.

**Comment by Kurt57** [comment]
Hi @timokoenig ,

Thank you for your message.
I understood the problem and create a ticket in our backlog.

Many kind regards!
Fatih

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
