### ISSUE TITLE
Same certificate imported twice

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#167]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- App version: 1.19

## Describe the bug

I am able to import a certificate twice If the data in the QR code contains a leading or trailing space.

## Steps to reproduce the issue

DEMO certificates

```
HC1:6BFOXN%TSMAHN-HWWK2RL99TEZP3Z9M52RAD1WG%MPG*IDJ57PA766$VA9IEPUCF/8X*G-O9 WUQRELS4AETO8FB+2M5536DOWCN8T%*400TFMVU1JLXKEV4L%4NS4KCTX*SZK7FQVUXG+TVEHNVGV6AL**IZMVD0H+BNOA7VH7NS4.$S6ZCJKBKC3KD34LT383N:IN1MPF5RBQ746B46O1N646RM93O5RF6$T61R63B0 %P/IE%TE6UG+ZEAT1HQ13W1:O1 SI5K1*TB3:U-1VVS1UU15%HIMI4UUFTIWMA4SISH9WVHPYH9UE*P1NX1JL89V9ON139G%E5/974ITN$K-PSB 8%SQU IQUSW*PW$PBCK L6VOE:OQPAU:IAJ0AZZ0OWCR/CSP4*2DL43U*0CEBQ/GXQFY73ARNNRTSLJZ73ZQJY$BT3E9%TGST:S23J3UQT8/DCCCD$21NDA-D:FLH0JF0JEYI1DLZZL1629HOR%N6GWD/RQ/6J 8VU2NCJ:DUHUTOFQGWMK96CFCI0OU1WBHJ6 0ZTR3:9C VB5G.BBILCH3W3-QZSDHZMH+GXVPDGW4PN/EAPDW000H%J$YH
```

```
 HC1:6BFOXN%TSMAHN-HWWK2RL99TEZP3Z9M52RAD1WG%MPG*IDJ57PA766$VA9IEPUCF/8X*G-O9 WUQRELS4AETO8FB+2M5536DOWCN8T%*400TFMVU1JLXKEV4L%4NS4KCTX*SZK7FQVUXG+TVEHNVGV6AL**IZMVD0H+BNOA7VH7NS4.$S6ZCJKBKC3KD34LT383N:IN1MPF5RBQ746B46O1N646RM93O5RF6$T61R63B0 %P/IE%TE6UG+ZEAT1HQ13W1:O1 SI5K1*TB3:U-1VVS1UU15%HIMI4UUFTIWMA4SISH9WVHPYH9UE*P1NX1JL89V9ON139G%E5/974ITN$K-PSB 8%SQU IQUSW*PW$PBCK L6VOE:OQPAU:IAJ0AZZ0OWCR/CSP4*2DL43U*0CEBQ/GXQFY73ARNNRTSLJZ73ZQJY$BT3E9%TGST:S23J3UQT8/DCCCD$21NDA-D:FLH0JF0JEYI1DLZZL1629HOR%N6GWD/RQ/6J 8VU2NCJ:DUHUTOFQGWMK96CFCI0OU1WBHJ6 0ZTR3:9C VB5G.BBILCH3W3-QZSDHZMH+GXVPDGW4PN/EAPDW000H%J$YH 
```

## Expected behaviour

A certificate should only be imported once.

## Possible Fix

Either trim spaces in the QR code or use the UVCI to identify certificates.

**Comment by Kurt57** [comment]
Hi @timokoenig  ,

Thank you for your message.
I understood the problem and create a ticket in our backlog.

How likely do you think this problem is to occur?

Many kind regards!
Fatih

**Comment by timokoenig** [comment]
Not very likely but still possible. A simple `trim` would already solve this

**Comment by Kurt57** [comment]
Hey @timokoenig. Should be resolved, can you confirm and close.

**Comment by timokoenig** [comment]
I can't because of https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/193

**Comment by Kurt57** [comment]
Hi @timokoenig its now released. Can you please check and close if solved?
