### ISSUE TITLE
App shows "Im Reiseland ungültig" although I'm checking for the rules inside of Gernany

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#168]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 15.3.1
- App version: 1.19

## Describe the bug

The app shows that a certificate is invalid in the "Reiseland" although I selected the rules for inside of Germany to be checked.

## Steps to reproduce the issue

1. Tap on "Gültigkeit prüfen"
2. Select "Deutschland - Inlandsregeln"
3. Have a certificate which does not fulfill these rules
4. See that the app shows "Im REISEland ungültig" 

## Expected behaviour

The app should not talk about a "Reiseland" when I'm checking the local rules.

## Possible Fix

Change the wording.

**Comment by Kurt57** [comment]
Hi @Ein-Tim ,

Thank you for your message.
I understood the problem and create a ticket in our backlog.

Many kind regards!
Fatih

**Comment by Ein-Tim** [comment]
@Kurt57 This issue persists. Will it be fixed soon?

**Comment by Kurt57** [comment]
Hi @Ein-Tim not yet but hopefully soon. We are working hard on some new features. Afterwards hopefully the bug will find its way to one of the next sprints.

**Comment by Kurt57** [comment]
Since check validity feature is not available anymore, I close this issue.
