### ISSUE TITLE
CovPass sometimes shows second name of certificate holder and sometimes not

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#169]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 15.4
- App version: 1.19

## Describe the bug

If certificates with and without middle name from one person are grouped, CovPass sometimes shows the middle name & sometimes not.

## Steps to reproduce the issue

1. Add a certificate with only only fore- & surname
2. Add another certificate for the same person with forename, middle name & surname
3. See that only fore- & surname are shown
4. Repeat steps 1 &2 for another person
5. See that fore-, middle & surname are shown

## Expected behaviour

Consitent behaviour, either always show middle name or never show it.

## Additional context

I can provide example certificates via Mail if necessary.

**Comment by Kurt57** [comment]
Hi @Ein-Tim ,

We display the information from the prioritize certificate on the home page and the detail page of a person. 

If this certificate has a middle name it will be displayed. I think the problem, if you can call it a problem, is during the creation of a certificate that sometimes the middle name is used and sometimes not.

Also within a person this "phenomenon" can occur with the same person when this person scans a certificate. 
- If this new certificate has/had more priority than the current one.
- If this certificate contains a middle name, while the old one does not. Or vice versa

Regards,
Fatih

**Comment by alexcimander** [comment]
Hi Tim,

we discussed the issue and the app will show the full name if typed in correctly by the issuers. A name that it put together by the information stored in all present certificates adds massive complexity which should be avoided. Therefore we suggest to cancel the issue, would you agree on that?

Best Regards,

Alex

**Comment by Ein-Tim** [comment]
@alexcimander 

Okay, understood, sounds good.
