### ISSUE TITLE
(De-)Selecting certificate as favorite takes too long (certificate is only marked as favorite after some seconds)

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#170]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone xR & iPhone 6s
- OS version: 15.4
- App version: 1.19

## Describe the bug

Clicking on the star icon on a person to select it as favorite first does nothing. After app. 3 seconds the certificate is marked as favorite. 
Same with deselecting a person as favorite.

## Steps to reproduce the issue

1. Tap on the star icon on a person
2. See that it takes some seconds until the star icon turns white and the certificate becomes the favorite

## Expected behaviour

No delay.

**Comment by timokoenig** [comment]
@Ein-Tim how many certificates do you have in your CovPass?

**Comment by Ein-Tim** [comment]
@timokoenig 8 persons. Do you need the exact number of certificates?

**Comment by timokoenig** [comment]
No that's fine. I can confirm this issue with about 25 certificates. It even takes a few seconds until the star initially appears on the detail screen

**Comment by Ein-Tim** [comment]
Do you know how the performance is with only 2/3 certificates? 

I would test it but tbh I don't want to delete all the certificates and rescan them.

**Comment by timokoenig** [comment]
This might be a general issue with the saved certificates because with the app that has 25 certificates, it takes a few seconds for the certificates to appear. Without knowing it I would think all my certificates are gone

**Comment by Kurt57** [comment]
Hi @Ein-Tim 

thank you for this issue. I will create an internal ticket that this get tracked. 
I think we will handle both: this ticket and #172  together.

Regards,
Fatih

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
