### ISSUE TITLE
How are persons sorted?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#171]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
I'm having all my certificates stored on 4 devices.
Only on two devices the certificates are sorted in the same way as on the other. On the other two devices the certificates are sorted in another sequence.
I have not marked any person as favorite. 
How exactly are certificates sorted and why does the app sort differently on different devices?

**Comment by Kurt57** [comment]
Hi @Ein-Tim,

thank you for your message.
First of all which sort do you mean. In the Detail page of a Person in the bottom? 

Regards,
Fatih

**Comment by Ein-Tim** [comment]
@Kurt57 

Hi Faith, 
no I mean the order in which persons are listed when opening the app.
I thought they are sorted by alpahbetical order, however, I now see that this is not always the case.

**Comment by Kurt57** [comment]
There is no explicit sorting logic, only if available, the favorite is displayed at the beginning. Implicitly, it could be that the person's certificates are displayed further up.

**Comment by Ein-Tim** [comment]
So the app just shows the people in a random order?

**Comment by Kurt57** [comment]
Yes

**Comment by timokoenig** [comment]
So why not set a fixed order? eg. alphabetical

**Comment by Kurt57** [comment]
You can convert your question into a enhancement @Ein-Tim

**Comment by Ein-Tim** [comment]
@Kurt57 

I'll do this at a later point of time. Thanks for answering!
