### ISSUE TITLE
Option to mark certificate as favorite on detail screen only appears after some seconds

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#172]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 15.4
- App version: 1.19

## Describe the bug

The star in the upper right corner only appears after some seconds, here is a screen recording:

https://user-images.githubusercontent.com/67682506/158845349-75f2ffc3-add0-4108-999e-8a9305afc525.MP4

## Steps to reproduce the issue

1. Click on a person
2. See that the star only appears after some seconds in the upper right corner

## Expected behaviour

The star should immediately be visible.

**Comment by Kurt57** [comment]
Hi @Ein-Tim 

thank you for this issue. I will create an internal ticket that this get tracked. 

Regards,
Fatih

**Comment by Ein-Tim** [comment]
@Staeffy I'm not sure why you closed this issue, as it still occurs in my app (latest app version).

**Comment by Ein-Tim** [comment]
Re-Ping @Staeffy

**Comment by Staeffy** [comment]
@Ein-Tim I couldn't reproduce this anymore and looking at the history it seemed to be solved - but I can recheck within the team, if there is more we can do

**Comment by Ein-Tim** [comment]
@Staeffy Do you want a video?

**Comment by Staeffy** [comment]
@Ein-Tim I believe you, we will discuss internally what our options are to improve this - but currently it won't be prioritized

**Comment by Ein-Tim** [comment]
@Staeffy 

Sounds good, thanks!
