### ISSUE TITLE
Rename "Check validity" button to "Check Validity for Travel" (Align to CWA)

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#179]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The button in the top left corner of the CovPass app reads "Check validity"

## Suggested Enhancement
Rename the button to "Check Validity for Travel", that's the wording CWA uses. 

## Expected Benefits
This changes makes it clearer that clicking on the button does not replace scanning the certificate with CovPassCheck.

**Comment by Kurt57** [comment]
Hi @Ein-Tim ,

thank you for this enhancement. I have created a internal ticket to track this.

Regards,
Fatih

**Comment by Ein-Tim** [comment]
As CovPass also offers to check the rules for Germany, the button name is fine. Closing.
