### ISSUE TITLE
CovPass Check on iPad

### ISSUE THREAD

**Issue by Jens07** [Digitaler-Impfnachweis/covpass-ios#18]
Today our administrator installed the CovPass Check-App (Ver. 1.3) on my official iPad (6. Generation, Wi-Fi **without cellular** - A1893 - iPadOS 14.6). After the start, I saw the attached note on my display. "Internet connection necessary". But the internet connection works proper on all other apps. The inspection of my vaccination certificate fails every time. Can anyone reproduce this failure? I assume, it is the missing cellular module. But why?

On my private iPad, I haven't any problems with the actual CovPass Check-App (Ver. 1.3). It's an iPad Air 2, Wi-Fi **with cellular** - A1567 - iPadOS 13.7).

Thanks for your help!
regards

Jens

![2021 06 23 Fehlermeldung iPad](https://user-images.githubusercontent.com/68737429/123168527-688a7300-d478-11eb-8ebc-5bf1674e622b.png)

![Fehler 2](https://user-images.githubusercontent.com/68737429/123170645-0d0db480-d47b-11eb-86a3-4d48cc0e90f1.png)

![Fehler 3](https://user-images.githubusercontent.com/68737429/123170717-2282de80-d47b-11eb-9c36-98c3a6c7688c.png)

**Comment by martinknechtel** [comment]
I can reproduce the same on my iPad (no Cellular, just WiFi). On scanning the QR, the app tells me the certificate is invalid. On my iPhone the CovPass app scanned my certificate without any problems. Seems to be a problem on iPad only, not on iPhone.

**Comment by Jens07** [comment]
>Seems to be a problem on iPad only, not on iPhone.

I am not sure. There is an iPhone without cellular too. It's called [iPod](https://www.apple.com/ipod-touch/). Maybe there is the same problem? Unfortunately I haven't an iPod touch.

**Comment by timokoenig** [comment]
Interesting behavior that I haven't noticed yet, I will check it on a WiFi only device later

**Comment by martinknechtel** [comment]
Cannot reproduce it anymore on my 
- iPad WiFi, 7th generation, NW772B/A, iOS 14.6
- iPad Simulator in XCode: iOS 14.0, iPad 8th generation

**Comment by timokoenig** [comment]
I could not reproduce the issue yet. I tried it with multiple iPads (WiFi only) and the current CheckApp version 1.3

**Comment by Jens07** [comment]
> I could not reproduce the issue yet. I tried it with multiple iPads (WiFi only) and the current CheckApp version 1.3

Thanks a lot! I should note that we use an MDM in our mayor's office. My colleague has the same iPad and the same problem. Perhaps there is a setting that prohibits the internet access. But all other apps on my official iPad haven't any problems with the access. That was the reason why I couldn't imagine that it could be a setting problem on the iPad.

**Comment by jxn-30** [comment]
We're able to reproduce the same issue on a device without cellular.
Device: iPhone 7; iOS 14.2
AppVersion: 1.3

**Comment by timokoenig** [comment]
@Jens07 do you have a passcode on those devices?

**Comment by Dirk23** [comment]
I can reproduce the same on iPad 5. Gen only Wifi (no Cellular) and we use MDM too (Miradore)

**Comment by jxn-30** [comment]
> @Jens07 do you have a passcode on those devices?

Although I am not Jens:
We do not have a passcode set on the device.
MDM is **not** used in our case.

**Comment by timokoenig** [comment]
Then this issue is related to https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/6 and has nothing to do with WiFi or Cellular devices

**Comment by Dirk23** [comment]
Just tested in iPad Pro 11" (iOS 15 Beta) only Wifi and Can Not reproduce the problem

**Comment by Dirk23** [comment]
> I can reproduce the same on iPad 5. Gen only Wifi (no Cellular) and we use MDM too (Miradore)

This device has no Passcode

**Comment by Dirk23** [comment]
> Just tested on iPad Pro 11" (iOS 15 Beta) only Wifi and Can Not reproduce the problem.
> iPad is Not in an MDM

This Device has a Passcode

**Comment by Jens07** [comment]
> @Jens07 do you have a passcode on those devices?

I had no passcode on my official device. Now I installed it and the app works fine. I could check my vaccination certificate without any problems. Thanks to all who helped to identify the problem!

**Comment by Dirk23** [comment]
So the Solution is the Passcode?

**Comment by Jens07** [comment]
> So the Solution is the Passcode?

I would say it is a workaround. Try it! But look at https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/6#issuecomment-873115384. We will get a solution of this problem.

**Comment by Dirk23** [comment]
> > So the Solution is the Passcode?
> 
> I would say it is a workaround. Try it! But look at [#6 (comment)](https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/6#issuecomment-873115384). We will get a solution of this problem.

I tried it and after setting a Passcode the App works like a charm.

**Comment by timokoenig** [comment]
@Jens07 regarding the MDM issue more information will follow what needs to be done to make the continues update of the app work. In the meantime please update to the latest version 1.4.1 which includes a few bugfixes that make the certificate validation work even without initial update of the DSC list

**Comment by jleufgen** [comment]
@Jens07 can we close the ticket?

**Comment by jleufgen** [comment]
https://www.digitaler-impfnachweis-app.de/faq/#fragen-zu-den-technischen-details
