### ISSUE TITLE
Replace "Maximum valid until dd.mm.yyyy" on recovery certificates with "Positive test from dd.mm.yyyy" and do not show how long a recovery certificate is valid (Align to CWA)

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#180]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
CovPass shows a recovery certificate together with the information how long the recovery certificate is valid at maximum. 

## Suggested Enhancement
Do not show how long a recovery certificate is valid but only show the date of the positive test. 

## Expected Benefits
Each country has different rules on how long a recovery certificate is valid, here in Germany 3 months, in most other EU countries 6 months and in the Swiss 1 year. A general statement how long the recovery certificate is valid at maximum is therefore impossible and should be removed.

**Comment by Kurt57** [comment]
@Ein-Tim i have created a ticket for this, thank you.

**Comment by Staeffy** [comment]
We discussed this internally and got the approval to change the date for this case. We will do so in one of the upcoming releases ( either 1.39 or 1.40 )

**Comment by Ein-Tim** [comment]
- PR: https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/327

**Comment by Ein-Tim** [comment]
This has been implemented.
