### ISSUE TITLE
Release 1.22.1

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#181]
Please release the source code of version 1.22.1 and tag a new release. Thanks.

**Comment by Kurt57** [comment]
Hey @Ein-Tim 

its released: https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.22.1.1

**Comment by timokoenig** [comment]
What's the difference between release 1.22.1 and 1.22.1.1?

**Comment by Kurt57** [comment]
> What's the difference between release 1.22.1 and 1.22.1.1?

1.22.1.1 points to same commit, so deleted.
