### ISSUE TITLE
Wrong entry rules for Germany

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#190]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Irrelevant
- OS version: Irrelevant
- App version: Irrelevant

## Describe the bug

Currently, according to [Informationen zu Einreise­beschränkungen: Das gilt ab 1. Juni 2022 (Auswärtiges Amt)](https://www.auswaertiges-amt.de/de/quarantaene-einreise/2371468), there are no entry restrictions to Germany at all currently. It is not necessary to prove recovery, test or vaccination on entry.
However, the [entry/business rules](https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=DE) do not reflect this and thus, sometimes the "Check validity for travel" feature of the CWA & CovPass, as well as the CovPassCheck-App still invalidate some certificates, although they are valid and can be used.

## Expected behaviour

The rules should be adapted. I think it is possible to create a new general rule which overrules all other rules and is that no matter what certificate was checked, it is valid for travel (as there is no need of a certificate).

**Comment by Ein-Tim** [comment]
Thank you @kerstin-oppermann-tsi!

**Comment by Ein-Tim** [comment]
@kerstin-oppermann-tsi 

Hey Kerstin,

what was the result from the discussion with the BMG?

**Comment by kerstin-oppermann-tsi** [comment]
Hi @Ein-Tim as you can see [entry/business rules](https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=DE) the new general rule is uploaded now and the old ones are deleted. The discussion and decision took a while ;) so your question was on time ;)
