### ISSUE TITLE
Misleading text on "Erneuerung notwendig" screen

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#192]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 15.5
- App version: 1.26

## Describe the bug

<img src="https://user-images.githubusercontent.com/67682506/172600582-8f32d331-ce0a-43c3-94da-b66b1fa5e23d.jpeg" width="300">

On the "Erneuerung notwendig" screen the app says on the one side that the certificate is expired and then in the text it says that it soon expires. This makes no sense. 

## Steps to reproduce the issue

1. Import a technically expired certificate into the app
2. Start the renewal process
3. See the misleading text on the "Erneuerung notwendig" screen

## Expected behaviour

The texts should be consistent. Either the certificate is already expired (case 1) or the certificate is about to expired (2).

## Possible Fix

Add different strings fro case 1 & case 2.

## Additional information

Certificate used to test: https://github.com/denysvitali/covid-cert-analysis/blob/master/RESULTS.md#samplesbrandenburgtesttxt

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by Ein-Tim** [comment]
Fixed in 1.26.1.
