### ISSUE TITLE
Always publish source code when announcing a new release

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#199]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently, someone from the CovPass-Team announces a release via [GitHubs Discussions](https://github.com/Digitaler-Impfnachweis/covpass-ios/discussions) feature & no source code or GitHub release is created. 

## Suggested Enhancement
Please improve the release process. For doing so, I suggest the following steps:
1. Create a GitHub release as soon as the update becomes available in the Play Store
2. In this GitHub release include the updated source code 
3. Create the corresponding `release/x.xx` branch 
4. Update the `main` branch

If you still want to create a discussion for a release, feel free to do so, GitHub even offers to directly create a discussion from the release page.

## Expected Benefits
Community members don't always have to ask for updated code and this is just best practice / standard for an open source project.

**Comment by MoritzIBM** [comment]
Hi @Ein-Tim,
Thanks and good point! We are working on it and will improve the process for release 1.29.
Have a nice day and best regards!
Moritz

**Comment by Ein-Tim** [comment]
For iOS, that worked with 1.28. For Android, the source code isn't available yet.

**Comment by timokoenig** [comment]
We adjusted the process so that the source code will be published shortly after the app gets released. Please keep in mind that this won't be within minutes of a new release due to the fact that the dev team needs to be informed about the release.

**Comment by Ein-Tim** [comment]
@timokoenig Okay, thanks!
