### ISSUE TITLE
"+" symbol is cut off on some devices

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#2]
The "+" symbol is cut off on devices with a physical home button: 

<img src="https://user-images.githubusercontent.com/67682506/122276288-ee407880-cee4-11eb-97af-6801b8020364.jpg" width="300">

**Comment by timokoenig** [comment]
This has already been fixed in the next minor version

**Comment by timokoenig** [comment]
Version 1.3 just has been released in the AppStore which fixes the issue

**Comment by Ein-Tim** [comment]
Confirm fix.
