### ISSUE TITLE
Twitter Report: CovPass wrongly shows "Grundimmunisierung" instead of "Vollständig Geimpft"

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#200]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- OS version: Not relevant
- App version: 1.27

## Describe the bug

A user on Twitter contacted me via DM and reported the following:

CovPass shows "Grundimmunisierung" although I have the following certificates in my app:

1x "Impfung 1 von 1" (J&J)
1x "Impfung 2 von 1" (Moderna)
1x "Impfung 3 von 3"  (Moderna)
1x Certificate of Recovery

Still the app only shows "Grundimmunisierung" here:

<img src="https://user-images.githubusercontent.com/67682506/175769008-8480f44a-37a5-435e-bc71-6354e01bb2e9.jpeg" width="300">

## Steps to reproduce the issue

1. Import the same combination of certificates into the app
2. Look at the status

## Expected behaviour

CWA behaves correctly and shows 2G+ (fully vaccinated / boostered). CovPass thus shouldn't show "Grundimmunisierung" but rather "Vollständig Geimpft". 

### Preferred Fix

To make sure that CWA and CovPass do not show different vaccination status, I strongly suggest to implement CCL into CovPass ( see also #188). This requires a major effort one time, but afterwards all changes will be done by the CWA team and the CovPass-Team can forget about it.

### Quick Fix

Just fix this one case to show "Vollständig Geimpft". But that does not seem like a good solution as we don't know how many other certificate combinations currently show a wrong status in CovPass. 

## Additional context

This seems to be a regression, as version 1.26 showed this:
<img src="https://user-images.githubusercontent.com/67682506/175769303-7dfdff2c-c70d-4954-9c86-925b0f48df53.jpeg" width="300">

## Screenshots

Screenshot from the certificate on the check view:
<img src="https://user-images.githubusercontent.com/67682506/175769321-191c0f33-abf3-4279-9c94-e4a4adb0adf3.jpeg" width="300">

Screenshots from the list of certificates:
<img src="https://user-images.githubusercontent.com/67682506/175769366-8d01adba-2bf6-4c8c-b73a-123d7224807c.jpeg" width="300">

**Comment by MoritzIBM** [comment]
Hi @Ein-Tim,

Thanks! We are aware of that and have fixed it for the next release 1.28. Indeed, the app shows "Grundimmunisierung" on the certificate owners' detail screen, although the person has, for example, a booster (as it is indicated correctly on the other screens).

Best regards,
Moritz

**Comment by Ein-Tim** [comment]
That's fixed now.
