### ISSUE TITLE
Remove the "Valid from dd.mm.yyyy" from not yet valid certificates of recovery

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#202]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not releavnt
- OS version: Not relevant
- App version: Not relevant

## Describe the bug

CovPass currently displays "Valid from dd.mm.yyyy" if a certificate of recovery is not yet valid. According to the CWA team, it is not safe to display this information, see https://github.com/corona-warn-app/cwa-wishlist/issues/723#issuecomment-1180021482:

> The valid_from date for a recorvery certificate is used to calculate the effective validity (fachliche Gültigkeit) for the G status in Germany.
As the G status and the effective validity are country-specific properties (and not equally defined across Europe), this valid_from date cannot be shown initially.

## Steps to reproduce the issue

1. Add a not yet valid certificate of recovery to the app
2. Take a look at the certificate
3. See that the app displays "Valid from dd.mm.yyyy"

## Expected behaviour

As it is not safe to show this date, please remove it.

## Possible Fix

Remove the date. 

## Additional context

If you disagree with the CWA team, please share your reason in a comment so that I can take it back to the CWA team.

**Comment by timokoenig** [comment]
@Ein-Tim in the beginning when we implemented it the effective validity of recovery certificates were relatively similar in all member countries. This definitely changed over time and now varies between some countries. In my opinion a valid from date is always important to show otherwise you won't know when you can use your certificate. However since Germany removed all entry restrictions, such a date does not make sense at the moment therefore we could remove it.

**Comment by Ein-Tim** [comment]
@timokoenig Thanks for sharing your thoughts! Lets see what the team thinks.

**Comment by Kurt57** [comment]
Hi @Ein-Tim 

thank you. I have crated an internal ticket.

Regards,
Fatih

**Comment by Staeffy** [comment]
@Ein-Tim  We discussed this internally and received feedback from our stakeholders, that we should stick to displaying the valid from information.
The app is mainly focused on german users, who should be aware of when they can use the recovery certificate within germany.

**Comment by Ein-Tim** [comment]
@Staeffy Thank you, I relayed that information back to the CWA team and expect the feature to be implemented into CWA soon: https://github.com/corona-warn-app/cwa-wishlist/issues/723#issuecomment-1346737548
