### ISSUE TITLE
All process in the app are incredible slow

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#203]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- OS version: 15.5
- App version: 1.27

## Describe the bug

I was playing around with the app a bit, renewing some certificates, deleting old ones, importing certificates, creating printouts, etc. and I notice that the app is, especially compared to the CWA, who does the same tasks with ease and with 0 waiting times, CovPass is incredible slow! 

## Steps to reproduce the issue

Do the following tasks on an older iPhone (on newer iPhones CovPass is still slower than CWA, but it's not that bad there). To compare, do the same task once in CovPass & once in CWA.

1. **Delete a certificate**
	With CovPass you will notice that the certificates details stay open for ca 5 sec. and nothing happens
	With CWA you see that the certificate is deleted instantly
2. **Create a print out of a certificate**
	With CovPass, after you click on "Weiter" the app takes ca. 5 sec to create the PDF and open the share sheet
	With CWA, after you click on "Einverstanden" the app loads for a brief moment (>1 sec.) and a nice preview of the PDF opens
3. **Import a certificate**
	With CovPass, after scanning the QR code the app loads for some seconds
	With CWA, there is no loading at all after the QR code was scanned
4. **Open the app (cold start)**
	With CovPass, there is a time frame of a few seconds where the app shows that there are no certificates stored in the app, only to show the certificates after some seconds
	With CWA, certificates are instantly available after a cold start 

## Expected behaviour

The app shouldn't be that slow. 

## Additional context

I have the same amount of certificates stored in CovPass & CWA.

**Comment by timokoenig** [comment]
I noticed that as well and guess this has something to do with the additional checks we do if the certificate is still valid and so on. I will look into this issue on how we can improve it

**Comment by Ein-Tim** [comment]
@Staeffy You applied the label https://github.com/Digitaler-Impfnachweis/covpass-ios/labels/investigating to this issue ca. 3 months ago, is there any update available which you could share with us?

**Comment by Kurt57** [comment]
@Ein-Tim  is this still happening ?

**Comment by Ein-Tim** [comment]
Nope, that's fixed! Thanks for the reminder!
