### ISSUE TITLE
Export all certificates feature

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#206]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently it isn't possible to export all certificates stored in the CovPass app at one click.

## Suggested Enhancement
CWA gained a mass export feature in version 2.24 which allows the user to export all certificates into one PDF. CovPass should get a similar feature. 

## Expected Benefits
There are many use cases for this feature, e.g. creating a backup of all stored certificates. It could also be useful if one wants to switch devices.

**Comment by Ein-Tim** [comment]
Is someone still checking the CovPass issues?
This as well all other open issues I created in the past months didn't receive any feedback from the team at all.

**Comment by timokoenig** [comment]
@Ein-Tim I haven't looked at the export feature of CWA yet but do they export all certificates of all people in one PDF or do they split it by person?

**Comment by Ein-Tim** [comment]
@timokoenig Everything in one PDF.

**Comment by timokoenig** [comment]
ok thanks, I will take this request to the team.

**Comment by Staeffy** [comment]
We got feedback from our stakeholders that this feature is not wished for within CovPass, therefore I'm  closing this
