### ISSUE TITLE
What is the "Behördenfunktion"?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#210]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
Version 1.30 of CovPassCheck added a "Behördenfunktion", however, there is no documentation at all available explaining how the feature works or what it does. Could you please elaborate on what this feature does? Thanks!

**Comment by alexcimander** [comment]
Hi @Ein-Tim,

Die Behördenfunktion richtet sich ausschließlich an die Gefahrenabwehrbehörden und ermöglicht diesen, im Missbrauchsfall eine Sperrung durch das Robert Koch-Institut (RKI) zu veranlassen.
Sperrung bedeutet, dass das betroffene Zertifikat in der Corona-Warn-App und der CovPass-App der jeweiligen Person als ungültig gekennzeichnet wird. Auch die CovPassCheck-App weist die gesperrten Zertifikate als ungültig aus.

----------------------------------------------------------

The authority function is intended exclusively for the emergency response authorities and enables them to initiate revocation by the Robert Koch Institute (RKI) in the event of misuse.
Revocation means that the certificate will be marked as invalid in the Corona warning app and the CovPass app. The CovPassCheck app also shows the blocked certificates as invalid.

**Comment by Ein-Tim** [comment]
@alexcimander 

Thanks for elaborating! Maybe it would make sense to publish some documents on this in the https://github.com/Digitaler-Impfnachweis/documentation repo, together with risk assessment, and so on? 

Anyways, my question here has been answered.
