### ISSUE TITLE
Prepare for regulation/definition change: Fully vaccinated means 3x shots starting on 01.10.2022

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#211]
### This issue applies to both iOS & Android!

The BMG has published https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/ifsg/faq-ifsg.html which states includes the following paragraph:

![189435156-9f00481f-d024-4a8c-b998-b483ab858001](https://user-images.githubusercontent.com/67682506/189455316-4a2e49a5-0cde-4587-9156-de7115349c79.png)

This is in line with the legal text, located in §22a of the IFSG ([link](https://www.gesetze-im-internet.de/ifsg/__22a.html)).

Please prepare both CovPass & CovPassCheck in time to
a) correctly show the status of their vaccination to the user
b) inform the user that there is need to have a 3rd shot if they want to continue to be "fully vaccinated"
c) reject 2/2 certificates (CovPassCheck)

**Please confirm that you saw this issue!**

## Related issues
- https://github.com/corona-warn-app/cwa-wishlist/issues/820
- https://github.com/corona-warn-app/cwa-app-ccl/issues/101

Thanks to @MikeMcC399 for creating these issues!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

You asked for some changes:

>Please prepare both CovPass & CovPassCheck in time to
>a) correctly show the status of their vaccination to the user

CovPass shows "Basic immunization" with a 2/2 certificate. This is correct.
CovPassCheck checks against 3G and 2G+ (see comments below).

>b) inform the user that there is need to have a 3rd shot if they want to continue to be "fully vaccinated"

This is a function of the booster rule texts. See also https://github.com/corona-warn-app/dcc-rule-translation/issues/10. To be consistent across CovPass and Corona-Warn-App if there is any change then it should be through the booster rules.

>c) reject 2/2 certificates (CovPassCheck)

CovPassCheck checks against 3G and 2G+ and I don't think that there is an active legal basis for these definitions any more. It seems that the framework for CovPassCheck would need to be revised. What rules should it check against and how should these be displayed? What about planned new optional state-based rules?

**Comment by Ein-Tim** [comment]
> CovPass shows "Basic immunization" with a 2/2 certificate. This is correct.

Not after 01.10.22, right? After 01.10.22 a 2/2 is not valid at all any more, or have I misunderstood something?

> To be consistent across CovPass and Corona-Warn-App if there is any change then it should be through the booster rules.

Yes, agreed.

> CovPassCheck checks against 3G and 2G+ and I don't think that there is an active legal basis for these definitions any more. It seems that the framework for CovPassCheck would need to be revised. What rules should it check against and how should these be displayed? What about planned new optional state-based rules?

I don't feel qualified enough to asses this situation and thus leave it to the team on how to interpret the legal changes.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> > CovPass shows "Basic immunization" with a 2/2 certificate. This is correct.
> 
> Not after 01.10.22, right? After 01.10.22 a 2/2 is not valid at all any more, or have I misunderstood something?

I think this is still correct after Oct 1, 2022. I'll switch to German because the reference material is in German.

Mit einem 2/2-Impfzertifikat zeigt CovPass "Grundimmunisierung" auf der Hauptseite an und empfiehlt über DE-BNR-0110 eine "Auffrischimpfung".

Wenn ein 3/3-Impfzertifikat in CovPass eingescannt wurde, zeigt CovPass "Auffrischimpfung" auf der Hauptseite an.

Neuerdings wird bei über 60-Jährigen mit einem 3/3-Impfzertifikat eine weitere Auffrischungsempfehlung über DE-BNR-0400 angeraten. Mit einem 4/4-Impfzertifikat ist der Status auf der Hauptseite auch weiterhin "Auffrischimpfung".

Hier werden die Begriffe "Grundimmunisierung" und "Auffrischimpfung" aus dem STIKO-Dokument im CovPass App verwendet: [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile).

Das Gesetz [IfSG § 22a](https://www.gesetze-im-internet.de/ifsg/__22a.html) kennt weder den Begriff "Grundimmunisierung" noch "Auffrischimpfung".

---

CovPass hält sich also konform zu dem [STIKO-Dokument](https://www.gesetze-im-internet.de/ifsg/__22a.html). Ich würde nicht erwarten, dass die STIKO-Begriffsdefinitionen in nächster Zeit sich ändern. Demnach wäre dann diesbezüglich keine Änderungen an der CovPass App notwendig.

Die Regeln "Gültigkeit prüfen" hängen allerdings in der Luft. Es ist in der App die Beschreibung von "Einreiseregeln". Laut [BMG: Aktuelle Informationen für Reisende](https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/guv-19-lp/coronaeinreisev.html) sind die Regelungen zum 1.6.2022 weitestgehend aufgehoben und, wenn ich es richtig sehe, läuft das Gesetz [Coronavirus-Einreiseverordnung (CoronaEinreiseV) § 14](https://www.buzer.de/14_CoronaEinreiseV.htm) ohnehin zum 30. September 2022 aus. Das ist eigentlich ein Thema für sich - wie viel von den bestehenden CovPass und CovPassCheck Apps sollen diesbezüglich beibehalten bzw. überarbeitet werden?

**Comment by Ein-Tim** [comment]
@MikeMcC399

Danke für deinen ausführlichen Kommentar! Ich vermute, das Hauptproblem ist zwischen der fachlichen Gültigkeit (STIKO Empfehlungen) & der rechtlichen Gültigkeit (IFSG) zu unterscheiden und das dem Nutzenden klar zu kommunizieren.

IfSG § 22a beginnt wie folgt:

"(1) Ein Impfnachweis ist ein Nachweis hinsichtlich des Vorliegens eines vollständigen Impfschutzes gegen das Coronavirus SARS-CoV-2 in deutscher, englischer, französischer, italienischer oder spanischer Sprache in verkörperter oder digitaler Form. Ein **vollständiger Impfschutz** gegen das Coronavirus SARS-CoV-2 liegt vor, wenn

1. die zugrundeliegenden Einzelimpfungen mit einem oder verschiedenen Impfstoffen erfolgt sind, die
	a) von der Europäischen Union zugelassen sind oder
	b) im Ausland zugelassen sind und die von ihrer Formulierung her identisch mit einem in der Europäischen Union zugelassenen Impfstoff sind,
2. insgesamt **drei Einzelimpfungen** erfolgt sind und"

Ich verstehe das so: Ein vollständiger Impfschutz liegt nur dann vor, wenn insgesamt drei Einzelimpfungen erfolgt sind. **Das bedeutet, wenn keine drei Einzelimpfungen erfolgt sind, ist der Impfschutz de-facto unvollständig (also rechtlich nicht Gültig)**, außer, ich zitiere weiter aus dem Gesetzestext:

"1. die betroffene Person einen bei ihr durchgeführten spezifischen positiven Antikörpertest in deutscher, englischer, französischer, italienischer oder spanischer Sprache in verkörperter oder digitaler Form nachweisen kann und dieser Antikörpertest zu einer Zeit erfolgt ist, zu der die betroffene Person noch keine Einzelimpfung gegen das Coronavirus SARS-CoV-2 erhalten hatte,
2. die betroffene Person mit dem Coronavirus SARS-CoV-2 infiziert gewesen ist, sie diese Infektion mit einem Testnachweis über einen direkten Erregernachweis nachweisen kann und die dem Testnachweis zugrundeliegende Testung
	a) auf einer Labordiagnostik mittels Nukleinsäurenachweis (PCR oder weitere Methoden der Nukleinsäureamplifikationstechnik) beruht sowie
	b) zu einer Zeit erfolgt ist, zu der die betroffene Person noch nicht die zweite Impfdosis gegen das Coronavirus SARS-CoV-2 erhalten hat, oder
3. die betroffene Person sich nach Erhalt der zweiten Impfdosis mit dem Coronavirus SARS-CoV-2 infiziert hat, sie diese Infektion mit einem Testnachweis über einen direkten Erregernachweis nachweisen kann und die dem Testnachweis zugrundeliegende Testung
	a) auf einer Labordiagnostik mittels Nukleinsäurenachweis (PCR oder weitere Methoden der Nukleinsäureamplifikationstechnik) beruht sowie
	b) seit dem Tag der Durchführung der dem Testnachweis zugrundeliegenden Testung 28 Tage vergangen sind."

---

Lass uns doch mal ein konkretes Beispiel anschauen. Jemand hat nur das Zertifikat der 2. Impfung in seiner App. Was sollte CovPass diesem Nutzenden nach dem 01.10.2022 anzeigen? Ich denke, CovPass sollte "Unvollständiger Impfschutz" anzeigen. Stimmst du mir zu?
CovPassCheck sollte ein reines "2/2" Zertifikat nach dem 01.10.2022 auf jeden Fall immer ablehnen, denn es zertifiziert keinen vollständigen Impfschutz, eine Impfung fehlt.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Jemand hat nur das Zertifikat der 2. Impfung in seiner App. Was sollte CovPass diesem Nutzenden nach dem 01.10.2022 anzeigen? Ich denke, CovPass sollte "Unvollständiger Impfschutz" anzeigen. Stimmst du mir zu?
CovPassCheck sollte ein reines "2/2" Zertifikat nach dem 01.10.2022 auf jeden Fall immer ablehnen, denn es zertifiziert keinen vollständigen Impfschutz, eine Impfung fehlt.

Die App-Verantwortlichen müssen festlegen, was das Ziel der Anzeige ist und daher, was richtig ist. Ich kann nicht mehr dazu beitragen, als ich bereits geschrieben habe.

**Comment by MikeMcC399** [comment]
According to https://github.com/corona-warn-app/cwa-app-ccl/pull/105 the upcoming CWA 2.27 release will remove the 2G/3G status display. I wonder what the plans for CovPassCheck are?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Maybe you want to open a new issue reg this? I'm also interested in the answer to this question!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Maybe you want to open a new issue reg this? 

Perhaps somebody from the development team will respond here?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

That would be good in any case!

**Comment by alexcimander** [comment]
Hello everyone,

we are working on an implementation to show new mask regulations and the new vaccination status. We will gradually expand the apps in releases 1.32 to 1.34.

We will initially include the new display of mask regulations and vaccination status in CovPass. As it is currently not clear  to what extent federal states will introduce mask regulations beginning in october we will prepare a federal-state-level display but we cannot promise to have it in full functionality released. But expect a enhanced mask-regulations display for CovPass within the next couple of weeks.

However we also focus on the mask-regulation check on federal state level with the Check app. We will introduce a new scan flow which allows you to check current mask regulations for your federal state. Doing that we want to introduce it as data-saving as possible. Checking your G-Status with CovPassCheck will be prepared, however for now there is no need to check the G-Status with the Check-App.

We are on it! 👨‍⚕️ 👩‍⚕️  Bear with us - we will provide you further updates as soon as possible.

Thank you everyone!

**Comment by Ein-Tim** [comment]
Implemented with 1.32
