### ISSUE TITLE
Why is vaccination + recovery not 2G+?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#217]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
Wehen I scan a vaccination certificate (vaccination on 17.09.2021) & a recovery certificate (positive test from 26.01.2022) CovPass says that the recovery certificate is not valid and thus the 2G+ scan fails. Why is this the case?

**Comment by Staeffy** [comment]
Closing this, because 2G+ is not being tested anymore
