### ISSUE TITLE
CovPassCheck: "Zertifikat nicht gültig" screen leaves out important reasons why a certificate may be invalid

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#218]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- OS version: 16.0.2 / 10
- App version: 1.32

## Describe the bug

Scanning a certificate of recovery, which certifies a recovery from COVID-19 with the first positive test being on 26.01.2022, CovPassCheck shows this screen (iOS & Android are exactly the same):

<img src="https://user-images.githubusercontent.com/67682506/193451291-2cbf0a59-ced6-4208-b739-8eeef7f18173.jpeg" width="300">

In this screen, CovPassCheck only shows that a certificate may be invalid because it's signature is invalid or the QR code is not readable, however, it does give reasons like
- recovery is too long ago
- vaccination protection is not sufficient
- etc.

## Steps to reproduce the issue

1. Scan a certificate of recovery with positive test > 3 months ago
2. See that CovPassCheck shows the screen which leaves out important reasons why the certificate is invalid.

## Expected behaviour

The screen should also list non technical reasons for a certificate being invalid.

## Possible Fix

Add more details to the screen.

**Comment by Staeffy** [comment]
Thanks for raising this issue!
We discussed this internally and will add one more reason: the technical expirey of certificates ( Release 1.39).
The other points such as "recovery too long" ago or "vaccination not sufficient" are covered through other explanatory screens and should not lead to this screen. 
The "Zertifikat nicht gültig" screen should only show up, when the certificate scanned is technically invalid.

**Comment by Ein-Tim** [comment]
This has been fixed with https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.39.0.
