### ISSUE TITLE
CovPassCheck: Result view is shortly shown before QR code scanner opens

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#219]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 16.0.2
- App version: 1.32

## Describe the bug

The result view is shortly shown before the QR code scanner opens in the 2G+ check option: 

https://user-images.githubusercontent.com/67682506/193455155-7d91f125-813b-4df0-aea8-76ce57da9166.MP4

## Steps to reproduce the issue

1. Open CovPassCheck
2. Select "2G+ prüfen" on the top
3. Tap "Zertifikat scannen"
4. See that the result view is shown shortly before the actual scanner opens

## Expected behaviour

The result view should not be shown until there is actually a result that can be presented to the user. 

## Possible Fix

Maybe the QR code scanner is a subview of the result view and they have to be rearranged? Just a guess.

**Comment by timokoenig** [comment]
Thanks @Ein-Tim . I will look for a solution for the upcoming release 1.35

**Comment by Staeffy** [comment]
@Ein-Tim  do you still have that problem with the latest release ?

**Comment by Ein-Tim** [comment]
No, thanks!
