### ISSUE TITLE
Layout not working for iPhone SE (1st gen) and similar sizes

### ISSUE THREAD

**Issue by Pe-te** [Digitaler-Impfnachweis/covpass-ios#22]
Hi folks, the app seems designed for some bigger device, but there are still a lot of people who use the older and smaller phones.

The margins are huge, images and texts are huge, and you have to scroll to see anything.

Would be great if you can spend some energy looking into it.

Not sure what you see on a big screen, but would at least expect to see the QR-code and my Name (if it is two lines high) when I start the app.

Think the easiest way to detect those devices is to go by sceen width smaller than X, don't remember the value or which project I used it in. Think it was this simple check:
`    UIScreen.main.bounds.size.width <= 320`
source: https://stackoverflow.com/a/51264446

Then I would just shrink the top+bottom constraints inside and outside of the light blue box until all is visible directly.

**Comment by timokoenig** [comment]
We've seen the issue and the UI/UX people are looking into possible solutions for all screen sizes

**Comment by timokoenig** [comment]
We will further track the progress in https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/16 since this is a duplicate
