### ISSUE TITLE
Starring a certificate doesn't bring it to the first position in the app

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#222]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 16.1
- App version: 1.34

## Describe the bug

I have one certificate starred, however, this is not the certificate on the first position in the app.

## Steps to reproduce the issue

1. Update to version 1.34
2. Star a certificate
3. Close the app
4. See if the starred certificate is at the first position of the person list

## Expected behavior

The starred certificate should be the first one shown.

## Possible Fix

Restore the behavior of the app pre 1.34.

## Additional context

I did not check this issue under Android. Please check that.

**Comment by timokoenig** [comment]
@Ein-Tim thanks for reporting this bug. I will check it

**Comment by Ein-Tim** [comment]
I can't reproduce this bug under Android.

**Comment by timokoenig** [comment]
I can confirm it on iOS and will provide a fix for the next version

**Comment by Ein-Tim** [comment]
Fixed in version 1.36.

**Comment by Ein-Tim** [comment]
@Staeffy could you re-open this issue please?

**Comment by Staeffy** [comment]
Thanks for your Feedback @Ein-Tim, we will have a look on that!

**Comment by Staeffy** [comment]
@Ein-Tim We fixed it and it should work again with Release 1.37 coming out next week!

**Comment by Ein-Tim** [comment]
Closing as fixed.
