### ISSUE TITLE
App does not delete certificates, although I get the "Erfolgreich gelöscht" pop up

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#223]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 16.1.1
- App version: 1.34

## Describe the bug

I attempted to delete two certificates from the app and got the "Erfoglreich gelöscht" pop up. However, when I open the person detail screen again, the certificates appear again. Only an app restart fixed this problem for me. 

## Steps to reproduce the issue

1. Attempt to delete the certificate of a person from whom you have multiple certificates stored in the app
2. See the "Erfolgreich gelöscht" pop up
3. Check the list of stored certificates for this person again and notice that the certificates which should be deleted are still there

## Expected behavior

The app should delete certificates, especially when it showed me the "Erfolgreich gelöscht" pop up. 

## Possible Fix

Probably some data storing issue. 

## Additional context

I can provide a video, which includes personal data, via mail if you give me a secure mail address.

**Comment by Staeffy** [comment]
Thanks for raising this bug!
I cannot reproduce this behaviour, but we will investigate it

**Comment by Kurt57** [comment]
@Ein-Tim do you have more information how to reproduce? could you even reproduce with latest version?

**Comment by Ein-Tim** [comment]
Can't reproduce it anymore.

**Comment by Staeffy** [comment]
thanks for confirming - I added it to the release notes
