### ISSUE TITLE
CovPassApp V1.37 and CovPassCheckApp V1.37 are both crashing right after launching

### ISSUE THREAD

**Issue by Ron-70** [Digitaler-Impfnachweis/covpass-ios#224]
CovPassApp V1.37 and CovPassCheckApp V1.37 are both crashing right after launching. 

## Technical details

- Device name: iPhone 6
- OS version: iOS 12.5.6
- App version: 1.37

## Describe the bug
Both apps crash right after launching. So for me they are not useable anymore.
Besides there are a lot of user complains now about this on the Apple App Store regarding this crash on iOS 12.x after the last update.

## Expected behaviour
Working App under iOS 12.1 as advertised in the App Store compatibility section.

## Additional context
I provide the iOS crash dumps for CovPassApp and CovPassCheckApp as attachment here for further analysis.

[CovPassApp-2022-12-07-101552.ips.zip](https://github.com/Digitaler-Impfnachweis/covpass-ios/files/10174763/CovPassApp-2022-12-07-101552.ips.zip)
[CovPassCheckApp-2022-12-07-101618.ips.zip](https://github.com/Digitaler-Impfnachweis/covpass-ios/files/10174765/CovPassCheckApp-2022-12-07-101618.ips.zip)

**Comment by Ein-Tim** [comment]
Please re-check with https://github.com/Digitaler-Impfnachweis/covpass-ios/releases/tag/v1.37.1 installed.

**Comment by Ron-70** [comment]
I rechecked with V1.37.1 and both apps are working now.

**Comment by iceweasel1** [comment]
Ich habe heute (14.12.22) das aktuelle Update V1.37.1 aufgespielt. Wurde mir heute als Neuste angeboten. Die App friert sofort beim Starten ein. Nichts funktioniert. Die Rezessionen im AppStore weisen auch darauf hin. Auch bei den vorherigen Update-Versionen, das es immer wieder einfriert.

Warum wird dies konsequent ignorierst/nicht behoben und mit jedem weiteren Update nicht ausmerzt?

iOS 16.2 (ebenso unter 16.1.2)
iPhone 12 Pro Max

**Comment by Ein-Tim** [comment]
@iceweasel1 

Kannst du bitte einen neuen Issue dafür öffnen?

Ich habe dieses Problem auf iOS 16.2 nicht.
