### ISSUE TITLE
1.39 iOS GitHub release?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#226]
* [X] None of the other issue templates apply to this issue.

@staeffy You created https://github.com/Digitaler-Impfnachweis/covpass-android/releases/tag/v-1.675.0 for Android, will there also be a 1.39.0 GitHub release for the iOS repo?

**Comment by Staeffy** [comment]
yes, it's coming :)

**Comment by Ein-Tim** [comment]
Ok, thanks! I'll close this issue as soon as it is available!

**Comment by Kurt57** [comment]
done @Ein-Tim
