### ISSUE TITLE
Privacy Note text is too small

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#3]
The text of the privacy note of the CovPass app is too small, it's hardly readable without zooming in. This should be changed for a better UX. 
<img src="https://user-images.githubusercontent.com/67682506/122277528-47f57280-cee6-11eb-9eba-fae920af2007.png" width="300">

**Comment by timokoenig** [comment]
Totally agree with you

**Comment by timokoenig** [comment]
Version 1.3 just has been released in the AppStore which fixes the issue

**Comment by Ein-Tim** [comment]
Confirm fix.
