### ISSUE TITLE
Add more specific details to front card

### ISSUE THREAD

**Issue by kNsja5w** [Digitaler-Impfnachweis/covpass-ios#30]
When showing the QR code with an incomplete vaccination status in restaurants and other venues (which do not use the scanner app, but read it personally), it seems hard to recognize what vaccination status the person has.

For a better and faster understanding, the following things could be implemented to improve the UX:

Current state after the first dose:
"Unvollständiger Impfschutz"

**Improvement:
"Dose 1 von 2. Tage seit Impfung: nn"**

Current state after second dose from day 1 to day 14:
"Vollständig ab dd.mm.yy"

**Improvement:
"Dose 2 von 2. Tage seit Impfung: nn"
Vollständiger Schutz ab dem dd.mm.yy"**

That would solve several problems at once:

- In e.g. Austria, testing is not required after the 22nd day after the first vaccination. By showing how many days have passed, it is easy to read, calculating is not required. 

- by showing the exact number of the doses that were administered, no one needs further understanding. At the moment, "Unvollständiger Impfschutz" and "Vollständig ab..." mean the same for readers; which doses did the person get until now? Not everyone knows the specific terms of this app.

<img width="322" alt="Bildschirmfoto 2021-07-01 um 22 19 16" src="https://user-images.githubusercontent.com/16246095/124184826-6b114c00-daba-11eb-9145-ac40b165ead8.png">
<img width="322" alt="Bildschirmfoto 2021-07-01 um 22 19 23" src="https://user-images.githubusercontent.com/16246095/124184830-6c427900-daba-11eb-824f-f6e6a1014527.png">

**Comment by jleufgen** [comment]
I understand the point, however it is not desired that we add more info to the front card due to data sparsity and the QR code should be digitally validated as it is more secure.
