### ISSUE TITLE
CovPassCheck is in Offline-Mode

### ISSUE THREAD

**Issue by mttkrb** [Digitaler-Impfnachweis/covpass-ios#32]
In the main screen there is a notification that the App is in Offline mode. last update 1.1.1970.

My device is: Iphone 12 with IOS 14.6
Connection: WLAN and LTE
App-Version: 1.4

![IMG_1099](https://user-images.githubusercontent.com/21170293/124762222-f6fbfb80-df32-11eb-842e-ec5ea78c9969.PNG)

**Comment by timokoenig** [comment]
@mttkrb Do you have a passcode on that device?

**Comment by no000wa** [comment]
I have the same problem, in the same situation: iPhone 12, IOS 14.6, covpass check app 1.4 (1), passcode is set.
The app is working well (as far as I could test it in a few hours, BUT there is this nasty screen notification 
![image](https://user-images.githubusercontent.com/87084967/124790780-c07eaa80-df4b-11eb-82b8-2b635e210738.png)
How can I change to the online modus?

**Comment by timokoenig** [comment]
I will have a look

**Comment by timokoenig** [comment]
It seems like the DSC list does not get updated therefore the error message above

**Comment by no000wa** [comment]
I installed the CovPass Check App today!

no000war

**Comment by mttkrb** [comment]
I just installed the app today. No MDM ist installed. Just Face-Id to protect the device.

**Comment by Ein-Tim** [comment]
Than that's probably the explanation why the date is 01.01.1970, for me I guess it's just the latest date CovPassCheck update the DSC list.

**Comment by timokoenig** [comment]
Can you please check again?

**Comment by Ein-Tim** [comment]
Works now 👍

**Comment by no000wa** [comment]
Ok now, thanks

**Comment by mttkrb** [comment]
works now
