### ISSUE TITLE
Display certificate revocation date

### ISSUE THREAD

**Issue by tdittmar** [Digitaler-Impfnachweis/covpass-ios#33]
Currently the CovPass app only displays the date the certificate was issued. I now read that the validity of the certificate is limited due to the currently unknown duration of the vaccination status (might be you need to boost after 8 months or so).

The German Corona Warn-App shows the certificate's validity as a time span. However, I've not found comparable information in CovPass.

Suggestion: Display the date the certificated becomes technically invalid prominently.

**Comment by Ein-Tim** [comment]
I would be really careful with that, see the discussion in https://github.com/corona-warn-app/cwa-documentation/issues/645.

**Comment by jleufgen** [comment]
Hi :) This is the issue of the expiration date, which is partially handled with the release 1.7!
