### ISSUE TITLE
Language of CovPass app can't be switched to english on a german iPhone

### ISSUE THREAD

**Issue by ctsde-markus** [Digitaler-Impfnachweis/covpass-ios#37]
Although there is a language setting in the app's settings, it doesn't really do anything.

- Device name: iPhone SE
- OS version: iOS 14.7.1
- App version: CovPass 1.4.2

## Describe the bug

In `settings` -> `CovPass` there is a section labelled "Preferred Language" ("Bevorzugte Sprache" of course it is) and i can choose either "Deutsch" or "English". But no matter what i select there, the app's language is always german.

Here my settings:

![Screen-Settings](https://user-images.githubusercontent.com/3747528/127744315-6f43150e-c244-40b1-8c0e-ea403413ade6.png)

Here the info page (as example) in the app, after changing to english and force-restart the app. Everything else is german only too.

![Screen-App-Info](https://user-images.githubusercontent.com/3747528/127744347-79c0f3f1-4976-4712-af5d-30b8b064fd5d.png)

Either you deliver the app in english, make the switch actually work or you remove the switch as long as there is no english translation. The current state is very confusing and leeds to  frustration.

**Comment by timokoenig** [comment]
Agreed, has already been fixed in the newest version that is about to be released
