### ISSUE TITLE
Make CovPass / CovPass Check available on other AppStores than DE

### ISSUE THREAD

**Issue by Tafkas** [Digitaler-Impfnachweis/covpass-ios#4]
Not sure if a GitHub issue is the right place to address this. Currently, the CovPass app is not available on the AppStore for the US. As I (and probably many more) don't have a German AppStore account I cannot install the app on my iPhone.

**Comment by Ein-Tim** [comment]
Same as https://github.com/Digitaler-Impfnachweis/documentation/issues/5

**Comment by apphancer** [comment]
It is also not available on AppStore for the UK. Corona-Warn also started like that - only for DE - they eventually released it on other stores. It would be good to see this rolled out on other stores too.

**Comment by HerrKevin** [comment]
I strongly encourage you to add this app to other App stores. There are many people in Germany who can't switch their app store for a variety of reasons. Given that this is an open source app, there's really no good reason to exclude international app stores.

**Comment by timokoenig** [comment]
This is something we are working on. Next up is the US AppStore and then the team will look into other countries. The app being open source doesn't make it easier or harder to release it in other countries. We always need to make sure that the whole product (apps and backend) stays compliant with the local laws.

**Comment by Ein-Tim** [comment]
@jleufgen 

I think this is the wrong issue? 😅

**Comment by jleufgen** [comment]
Hi all, the app will come for the US market with one of the next releases. Best regards!

**Comment by phonique** [comment]
Requesting to reopen the ticket until the app is available in other regions.
Specific request for the Russian app-store.

**Comment by jleufgen** [comment]
With the EU's digital COVID certificates, the EU member states have agreed on a common pattern that facilitates recognition both electronically and on paper. Accordingly, each EU state has its own system for issuing the certificates. The certificates can be used throughout the EU. Russia in particular is not currently discussed.

**Comment by phonique** [comment]
Thanks for the reply @jleufgen! 
What is the reasoning behind to the limitation of app distribution to a region?
I have a specific case of an expat, who has his phone bound to the Russian app-store but German vaccination certificates. What would be your proposed solution for such a case?

**Comment by Tafkas** [comment]
@phonique 

My current work around is to use the Swiss app https://github.com/admin-ch/CovidCertificate-App-iOS which is available in the US app store. It can store the German (European?) vaccination certificates and people are able to scan them with their apps. The only shortcoming is that the app cannot "validate" them.

**Comment by phonique** [comment]
Thanks @Tafkas, I will look into it. Not sure how the reaction to an "invalid" certificate will be at the door with people unaware of the issue. I guess, as long as covpass-check still works on those QRs it should be all right.

The issue remains, however, that @jleufgen 's reply does not answer the question, why the app is not available in other, non-EU markets, especially considering that the US store is made an exception.

**Comment by Tafkas** [comment]
@phonique The app shows validity in Switzerland and displays a remark "Only valid in combination with an identity document". So far everybody in Germany and Italy (who uses a system called green pass) has accepted it. Once somebody has scanned the QR code and it was valid, too.

I still think the "proper" solution would be to publish the app on more app stores.

**Comment by apphancer** [comment]
Has anyone tried with the Luca app? I have been able to install this on iOS using the UK App Store. The Luca app allows adding certificates including QR codes from vaccination certificates. I have been using the Luca app with a vaccination QR code successfully in Germany and other EU countries where everyone has been able to read from the QR code that is displayed.

**Comment by apphancer** [comment]
Considering this app has still not been made available to other App stores, I would like to suggest a few other valid alternatives in addition to the Luca app.
There are websites out there that allow for adding the QR code issued by pharmacies/test centres into an entry in Apple Wallet. In my opinion this is even a better option as it does not allow having any extra apps.

https://www.getcovidpass.eu/
https://covidpass.marvinsextro.de/ (https://github.com/covidpass-org/covidpass)

**Comment by ratkins** [comment]
> https://covidpass.marvinsextro.de/ (https://github.com/covidpass-org/covidpass)

I have generated an Apple Passbook pass via this site and have not had any trouble with it being accepted so far.

**Comment by davidfurlong** [comment]
Classic failure of government via bureaucracy. Pretty stupid that this isn't available in for example the dutch App store when Germany and the Netherlands have EU based cross border worker agreements. Going to try https://www.getcovidpass.eu/
