### ISSUE TITLE
Sort countries by name and not by TLD

### ISSUE THREAD

**Issue by Chefkeks** [Digitaler-Impfnachweis/covpass-ios#43]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Countries are sorted by top-level-domain (TLD) and not by name, so starting with Austria: at, .be, .bg, .ch, .cy, .cz and so on

## Suggested Enhancement
Sort countries by name (based on the app language) instead of TLD.
For example **S**pain (.es) is currently located between **E**stonia (.ee) and **F**inland (.fi) which is not really intuitive. Searching Spain for example takes you a while until you realize the list with countries is not sorted from A to Z. 🤦 

## Expected Benefits

Better user experience of course with a list sorted A-Z 😄

**Comment by timokoenig** [comment]
This is already fixed in the next version that is about to be released
