### ISSUE TITLE
CovPass Check App is called "Check Check"

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#44]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR 
- OS version: iOS 14.7.1
- App version: CovPassCheck 1.6 (1)

## Describe the bug

Since the latest update, the app is called "Check Check" instead of "CovPassCheck". 

<img src="https://user-images.githubusercontent.com/67682506/130334376-5a33df11-3865-4b8e-bd2b-50ef8cd4c810.PNG" width="300">

## Steps to reproduce the issue

1. Update CovPassCheck to its latest version
2. Search for CovPass using Spotlight on iPhone
3. See that CovPassCheck is called "CheckCheck"

## Expected behaviour

The App should be called "CovPassCheck".

**Comment by jleufgen** [comment]
Hello, thank you very much for the feedback! The bug will be fixed with the next release. Best regards!
