### ISSUE TITLE
CovPassCheck sows "01.01.1970" for most recent update of "Rules"

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#45]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: iOS 14.7.1
- App version: 1.6 (1)

## Describe the bug

CovPassCheck shows this: 
<img src="https://user-images.githubusercontent.com/67682506/130334467-3121f7c3-d595-4d9b-9bcb-5c21eafcd087.PNG" width="300">

## Steps to reproduce the issue
1. Update CovPassCheck to its latest version
2. See the wrong time.

## Expected behaviour

A realistic time should be shown.

**Comment by Ein-Tim** [comment]
I don't see this date anymore. 

Closing as fixed.

**Comment by timokoenig** [comment]
The initial update takes some time due to the amount of rules we need to load

**Comment by Ein-Tim** [comment]
@timokoenig 

Still showing "01.01.1970" is wrong. Should you ever add a new date there please make sure that also after the first start after the update a meaningful date is shown.

**Comment by timokoenig** [comment]
We already worked on that and will the introduced in the next version that is being released
