### ISSUE TITLE
"Display current QR code" button behaves very strange on starred certificate

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#46]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: iOS 14.7.1
- App version: 1.8 (1)

## Describe the bug

Clicking on the "Display current QR code" button on a starred certificate behaves very strange.
When "Display current QR code" is clicked, the app scrolls to the position were the certificate would be if it wasn't starred. However, as it was starred and thus is shown as the first one, a wrong certificate is shown.
When the user now selects the certificates which is shown to them (where the app scrolled to) and clicks on "Display current QR code" the app scrolls through the certificates. So when the app scrolled to the last certificate and the user now selects the certificate and clicks on "Display current QR code" the app scrolls to one certificate to the left. When the user now selects this certificate and clicks on "Display current QR code" the app, again, scrolls one certificate to the left. And so on and so on.

## Steps to reproduce the issue

1. Add multiple certificates to the CovPass-App
2. Star the very last certificate (the one on the very right)
3. Click on "Display certificates"
4. Click on "Display current QR code"
5. See that the app scrolls to the very right
6. Click on the certificate which is now shown
7. Click on "Display current QR code" 
8. See that the app scrolls one certificate to the left

## Expected behaviour

The current certificate should be shown. No scrolling is involved here. 

## Additional context

I can provide a video via E-Mail, as I do not have any mock certificates but only real ones.

**Comment by timokoenig** [comment]
@Ein-Tim thanks for reporting. I fixed something in a newer version and will check if I can reproduce the issue there

**Comment by Ein-Tim** [comment]
FYI: I can still reproduce this issue in version 1.8.

**Comment by timokoenig** [comment]
Just checked again. This will be fixed with the next release 1.9

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed in version 1.9.
