### ISSUE TITLE
"New Update available" pop-up is shown even after the app has been updated to the latest version

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#48]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- OS version: 14.7.1
- App version: 1.8 (1)

## Describe the bug

The "New Update available" pop-up is shown even after I updated the app to version 1.8. Clicking on "Update" just leads to the App Store Page of CovPass, but not with the "Update" but just with the button "Open". This also underlines that the app is already on the latest version.

## Steps to reproduce the issue

1. Open the App Store
2. Click on the top right corner on your profile picture
3. Pull down and update the list of available updates
4. Update CovPass
5. Open CovPass
6. See the pop up

## Expected behaviour

The pop up should only be shown when there really is an update available.

## Additional context

1. I observed the same behavior in with the update from version 1.6 to 1.7.
2. Same goes for CovPassCheck

**Comment by whiskey** [comment]
Hey Tim, the update check should get fixed in 1.9. I'll leave the issue open until it's release.

**Comment by Ein-Tim** [comment]
Thanks @whiskey!

**Comment by Ein-Tim** [comment]
I can confirm that this issue has been fixed in version 1.9.
