### ISSUE TITLE
 Release version 1.8 on GitHub and update Codebase

### ISSUE THREAD

**Issue by bottee** [Digitaler-Impfnachweis/covpass-ios#49]
## Avoid duplicates
* [x ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

On the App Store currently Version 1.8 is available. On Giithub I can only find Version 1.6

Last week I was able to scan an EU-Vaccination Zertificate with the codebase V1.6 found here on Github, yesterday I tried again and it was not possible anymore. 

## Steps to reproduce the issue

![IMG_3193](https://user-images.githubusercontent.com/9673390/132495236-329b585a-1d10-4a69-8856-18563f99f660.PNG)

## Expected behaviour

It would be nice if there would be always a working codebase on Github.

**Comment by timokoenig** [comment]
@bottee did you use the right configuration? It looks like you try to scan a production certificate with demo configuration or vice versa

I will upload the new version in a bit

**Comment by bottee** [comment]
Thank you @timokoenig for the response and the update. Unfortunatelly it is still not working. I even did a clean clone on a different computer. So here is what I did:

## Technical details

- Device name: iPhone XR & iPhone 7
- OS version: 14.7.1
- App version: origin/release/1.8 
- Macbook Pro (intel) and Macbook Air (M1)
- xCode 12.5.1 (12E507)
- Macos 11.5.2 (20G95)

## Describe the bug

The scan of a valid EU-COVID-Certificate does not succeed.

## Steps to reproduce the issue

For a screenshot of the error message, see [above](https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/49#issue-990994556)

1. `git clone https://github.com/Digitaler-Impfnachweis/covpass-ios.git`
2. `cd covpass-ios`
3. `./Scripts/copy-config-files.sh release`
4. Open covpass-ios in xCode
5. Select a valid Team for signing
6. Build and Run on iPhone XR or iPhone 7
7. Scan a valid EU-COVID-Certificate
8. Error Popup: "COVID-Zertifikat enthält keine gültige Signatur"

## Expected behaviour

Adding the EU-COVID-Certificate successfully

## Possible Fix

## Additional context

Last week I was able to scan an EU-Vaccination Zertificate with the codebase V1.6 found here on Github, 2 days ago I build and run the app again and it was not possible anymore.

**Comment by timokoenig** [comment]
@bottee please use the following config `./Scripts/copy-config-files.sh release-rki`. I will make it more clear with the config so it doesn't come to this confusion. Sorry for that

**Comment by bottee** [comment]
@timokoenig Bingo! That was it. Now it works. Thank you very much!

**Comment by timokoenig** [comment]
Awesome! I will update the documentation
