### ISSUE TITLE
Different date for "full protection" shown on different devices

### ISSUE THREAD

**Issue by tdittmar** [Digitaler-Impfnachweis/covpass-ios#5]
### Description
Scanned my official QR codes on my iPhone 7. My wife scanned her official QR code for the second vaccination on her iPhone SE 2016.
For backup, I scanned her QR code from her CovPass display and she scanned mine from my CovPass display.

### Expectation
Same output on both phones.

### Reality
The dates shown on my device are one day earlier than the dates shown on her device for both her and my entry.

### Checks performed
Both phones are set to automatic adjustment of date and time and both show the current date and time correctly.

**Comment by borispf** [comment]
I noticed a similar thing. The 1.0.2 update mentions a change to how the full protection date in calculated. Maybe you have different versions of CovPass running on the two devices?

**Comment by tdittmar** [comment]
Yes, that was it. My wife downloaded the app an hour ago, I downloaded it on Monday and didn't see the 1.0.2 update. After installing the update, the dates match.
