### ISSUE TITLE
Releases: Create a GitHub release for every version released in the App Store

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#52]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently there are only two releases here on GitHub, although there are more than two on the app store. This doesn't match.

## Suggested Enhancement
For future releases I think it would be good to always release a version here on GitHub, when you release this version in the App Store.
Maybe it would even be possible to write a (very short) summary what's included in this release? But that's not that important since release notes are in the App Store.

## Expected Benefits
Better overview over releases, more transparency.

## Additional information
I'm sure you'll do this @timokoenig? 🙂

**Comment by timokoenig** [comment]
Yes, I already added a new release for 1.9 and synced the code yesterday. I will look over the other releases and add the Changelog

**Comment by Ein-Tim** [comment]
@timokoenig 

I saw this, thank you! 

You can release past versions, but I'd not request this. As long as the future versions are released everything is fine 👍

Thank you for taking care!

**Comment by timokoenig** [comment]
I updated all previous releases with a short changelog

**Comment by Ein-Tim** [comment]
@timokoenig 

Thank you! Some questions:

1.0 in the App Store is 1.1.3 on GitHub? Or is version 1.1.3 everything from 1.0 - 1.02? Version 1.0.3 in the App Store is 1.1.4 here, or?
Version 1.4.2 is missing, but I guess that's not a problem.

Enjoy your evening!

**Comment by timokoenig** [comment]
I will check  1.1.4

The first two releases are different from the release number in the AppStore. This has been fixed with 1.3 and since then the release in the repository matches the AppStore version.

**Comment by timokoenig** [comment]
@Ein-Tim I added 1.4.2 as well. Thanks for noticing, I must have missed that one

**Comment by Ein-Tim** [comment]
Thank you @timokoenig!

**Comment by Ein-Tim** [comment]
Thank you @Kurt57!
