### ISSUE TITLE
Don't show the "New Features" Screen after the onboarding

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#53]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Currently, after the user has stepped through the onboarding, the app shows the "New Features" screen which doesn't really make sense to me, as a user which just finished the Onboarding won't know what "new" features are and what "old" features are, as all features are new to them.

Here's a video of the current implementation:

https://user-images.githubusercontent.com/67682506/136433030-c7cdd822-00ff-42ac-bd25-13fc46f1c080.mp4

## Suggested Enhancement
Don't show the "New Features" screen to users which have just onboarded the app.

## Expected Benefits
The user is less confused and the user has to click less buttons to access the core functionality of the app.

**Comment by alexcimander** [comment]
Hey Tim,
once again: Thank you for the feedback. We will discuss it in the team and I will drop you an update on that :-)

**Comment by alexcimander** [comment]
Hey everyone,

as you might noticed with the latest release the onboarding screens for updates and the "what is new"  for new installations are still present. Please bear with us - we did not forget it and we are working on it 🚧 🏗️ 

thank you!

**Comment by alexcimander** [comment]
**UPDATE:** This issue will be solved with the app version 1.16. 1.16 is planned to be released mid-january! 🚧 🏗️

**New behavior:** In cases of fresh installments no "what-is-new-screen" will be displayed after the onboarding is completed.

**Comment by timokoenig** [comment]
Should be fixed since 1.16 has been released

**Comment by Ein-Tim** [comment]
@timokoenig 

You're right, thanks!
