### ISSUE TITLE
App not accessible outside of German app store (iOS)

### ISSUE THREAD

**Issue by lohrmann** [Digitaler-Impfnachweis/covpass-ios#56]
I live in Australia (🦘) but will be travelling back to Germany for Christmas—turns out the app can't be downloaded on a non-German app store. 

There are currently two workarounds—but it would be great if the app download could not be region-restricted as there are several non-government apps that are using the same name  (some with in-app payments) that unsophisticated users may fall for.

Workarounds to get an official app working are:
* Temporarily switch the iOS app stores to the german app store, download the app, then switch back (requires a German credit card)
* Download the Austrian app which is available internationally and supports the German and EU-wider certificate (several other apps, e.g. Poland, Portugal, Italy, Cyprus or Switzerland are also available on the international app store)

**Comment by Ein-Tim** [comment]
Good Morning @lohrmann!

This issue was already raised multiple times, e.g. in #4 & in https://github.com/Digitaler-Impfnachweis/documentation/issues/5.
I'm sorry to say it, but it does not seem like a worldwide release will happen, for what reason whatsoever.

Have a nice day!
Tim

**Comment by davidfurlong** [comment]
Yeah so it's also not available to me in the dutch app store. And I can't change app stores because apple makes it really hard if you have active subscriptions. I'm pretty sure this is just a checkbox in the apple developer account, is there really no way to get this through?

**Comment by JilAuraya** [comment]
I completely understand your desire to have the apps in other App Stores as well. Currently, the CovPass is only available in the German and the US App Store. 
Nevertheless, for now, there are no intentions of opening the app to further app stores (regardless of the benefits). If you have another app store (not US or DE), we can only forward you to the Corona Warn App.

**Comment by jleufgen** [comment]
@lohrmann is it okay if we close this ticket?

**Comment by andy-vdg** [comment]
This app needs to be available in other app stores. It's the most infuriating thing when the Swiss Covid certificate is shown as invalid in the German Covpass checker app without ever having problems with it in Switzerland. In the app it says "The checked person can see the reason in their CovPass app". Well I can't because it does NOT show the reason in the Swiss Covid Cert app and I cannot download the Covpass app in the Swiss App Store.

**Comment by viegelinsch** [comment]
> I completely understand your desire to have the apps in other App Stores as well. Currently, the CovPass is only available in the German and the US App Store. Nevertheless, for now, there are no intentions of opening the app to further app stores (regardless of the benefits). If you have another app store (not US or DE), we can only forward you to the Corona Warn App.

Unfortunately the Corona Warn App (CWA) is not available outside EU and US.
Researchers and students from Russia and China currently have no possibility to safe their vaccination QR code on their device except of using the LUCA App. Writing this, it just happens that many German states do not prolong their contract with LUCA App.
So from my point of view publishing the CovPass App in more countries is a desirable outcome.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
