### ISSUE TITLE
Validation only for german dcc?

### ISSUE THREAD

**Issue by ChristianFranke** [Digitaler-Impfnachweis/covpass-ios#57]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File: https://github.com/Digitaler-Impfnachweis/covpass-ios/tree/main/Certificates/PROD
* Line(s): -
* Question: Is it correct that only the German DSC list is downloaded from Ubirch and thus only German issuers validate DCC certificates?

See also https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/main/Scripts/dsc-download.sh

**Comment by timokoenig** [comment]
CovPass only accepts EU Covid Certificates, therefore UK is not part of it. You can find a list of all connected countries here: https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en
