### ISSUE TITLE
iOS Widget showing QR code

### ISSUE THREAD

**Issue by vollkorntomate** [Digitaler-Impfnachweis/covpass-ios#59]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Suggested Enhancement
Add a widget extension to the iOS app (>= iOS 14) which displays the vaccination/recovery/test QR code marked as favorite. This allows for easy access on the Home Screen or Lock Screen without the need to unlock the device. This will be helpful in all situations where 2G/3G rules apply.
As a reference, I can recommend the official French app [TousAntiCovid](https://gitlab.inria.fr/stopcovid19/stopcovid-ios) which already provides this functionality.

**Comment by mansle** [comment]
As a modification of the initial proposal: QR should be integrated in the wallet on iOS. In particular, this would not require the laborious unlocking of the iPhone (FaceID does not work because of the mask).

**Comment by Ein-Tim** [comment]
@mansle 

Please see https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/37.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
