### ISSUE TITLE
Why does CovPassCheck not show whether one scanned a vaccination or a recovery certificate?

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#60]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question
Why does CovPassCheck not show whether one scanned a vaccination or recovery certificate? Is there any reason or is this just by coincidence?

**Comment by jleufgen** [comment]
Hi @Ein-Tim thanks for the question, due to privacy regulations we are not allowed to display this information.

**Comment by Ein-Tim** [comment]
@jleufgen 

Mh, okay. But if the user shows the QR code to the person checking with CovPassCheck, the person checking can easily tell whether one has recovered or is vaccinated from/against COVID-19 as 
1. CovPass either shows "Impfzertifikat" or "Genesenenzertifikat" on top of the screen and
2. Vaccination certificates and recovery certificates are shown in CovPass with a different blue tone.

If you really want to achieve what you started here, you should do it like the Corona-Warn-App and 
1. Not show "Impfzertifikat" or "Genesenenzertifikat" at the top but just "Digitales COVID-Zertifikat der EU" and
2. Not show recovery and vaccination certificates in different blue tones.

Would you like me to open a new bug report for this?

**Comment by jleufgen** [comment]
@Ein-Tim In principle you are right, but this is no longer edited. It is also about the fact that the CovPassCheck app is "universal", so also for paper certificate and CWA.

**Comment by Ein-Tim** [comment]
@jleufgen 

> In principle you are right, but this is no longer edited.

Mh, okay, thanks for acknowledging! I understand that this is no longer edited, maybe it still makes sense to raise this to the RKI in the next product meeting? Just to make them aware of this inconsistency.

I, however, will no longer follow up on this topic and close this issue now.
