### ISSUE TITLE
Allow adding the QR code to Apple Wallet

### ISSUE THREAD

**Issue by lognseth** [Digitaler-Impfnachweis/covpass-ios#61]
It would be great if we could add the QR code to Apple Wallet from the Covpass app. It would be more easily available "at a glance". 

I guess [this](https://dailyhive.com/vancouver/covid-19-vaccine-passport-apple-wallet) isn't available in Europe yet for health care providers to use, but it would be very practical with something similar.

**Comment by Ein-Tim** [comment]
Same as https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/37?

**Comment by lognseth** [comment]
Oops, didn't see that.
