### ISSUE TITLE
All certificates are marked as invalid

### ISSUE THREAD

**Issue by fabfre** [Digitaler-Impfnachweis/covpass-ios#63]
## Avoid duplicates

- [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
- [x] Question has not already been asked in another issue

## Your Question

* Source File: HCert.swift
* Line(s): 59
* Question: I am building the Cov-Pass Check app with Xcode 13. I run the copy-config-files.sh file, it also copies the files. The App builds ans runs on my iPhone XR (passcode protected). Nevertheless all QR scans / certificates are marked as invalid. I have a complete trust list array. However, a HCertError.verifyError is thrown on every check. So I end up at line 59 (HCert.swift). I tried the debug scheme as well as release scheme.
Scanning the same QR codes / certificates using the Check App from the App Store results in the expected behaviour, all certificates are marked as valid. What am I doing wrong?

**Comment by timokoenig** [comment]
@fabfre do you try to scan production certificates?

**Comment by fabfre** [comment]
@timokoenig thanks for your answer. yes, i try to scan my own (real world) vaccination certificate. Does this imply that I need to build release-rki?

**Comment by timokoenig** [comment]
@fabfre Yes, execute `./Scripts/copy-config-files.sh release-rki` and try it again

**Comment by timokoenig** [comment]
You might want to delete the app as well to remove any debug DSCs that are in the keychain

**Comment by fabfre** [comment]
@timokoenig Thank you very much for your help. The scan and validation works now as expected.
One more question (I hope this one is still ok for this issue): are there any freely available debug certificates? Or can I make them myself using the the Certification API repo?

**Comment by timokoenig** [comment]
I'm glad I could help

You can find demo certificate from all European countries at https://github.com/eu-digital-green-certificates/dcc-quality-assurance, but be aware that some of them don't work because they already expired

**Comment by fabfre** [comment]
Perfect. Thank you for the fast support.
