### ISSUE TITLE
Rules distribution with non Monotonic version

### ISSUE THREAD

**Issue by ecki** [Digitaler-Impfnachweis/covpass-ios#64]
## Avoid duplicates
* [x ] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x ] Question has not already been asked in another issue

## Your Question
Is it correct that the current rules distribution point has vaccination rules with newer identifier but „older“ version number?

    ..
    {"identifier":"VR-DE-0003","version":"1.0.4","country":"DE","hash":"f19e4792aeaffc8aba2ad59a851cbd3ceea6c0f44cafdb31cbeea6a6dcc7610e"},
    {"identifier":"VR-DE-0004","version":"1.0.0","country":"DE","hash":"1313e59f84f472694eece639cbe955b5c469ed7e0adb319a731d2d77f62f3e31"}

**Comment by timokoenig** [comment]
This could be the case where an old rule got updated but instead of creating a new rule, the old rule got replaced. CovPass only uses those rules and doesn't create them. You might want to ask the question again in https://github.com/eu-digital-green-certificates/dgc-certlogic-ios
