### ISSUE TITLE
Generate QR-Codes differently

### ISSUE THREAD

**Issue by crownedsimon** [Digitaler-Impfnachweis/covpass-ios#66]
### **Problem:**
Certificate codes are currently the same as they are on the EU-Certificates for vaccinations.
Scanning a QR-Code out of the app with CovPass on any other device lets you add someone elses certificate to your own CovPass installation and vice versa.
Although the App should always only be used with CovPassCheck and an official ID, _that often isn't the case_, even in official control situations -> potential distribution of certificates among unvaccinated people.

### **Proposal:**
Change the way the QR-Codes are generated so that the only way of adding verifiable certificates to the app is by scanning _official_ and real _vaccination certificates_.

**Comment by Ein-Tim** [comment]
Related issue: https://github.com/ehn-dcc-development/hcert-spec/issues/107

**Comment by jleufgen** [comment]
@crownedsimon thank's! This topic is very interesting for us. We discuss this internally and then give feedback! :)

**Comment by alexcimander** [comment]
Hey @crownedsimon,

we got some news! We are currently working on several features that will further prevent the misuse of the CovPass-App as the "Check-App".

When it comes to a different QR-Code: We have to make sure that our app is compliant with the EU regulations and the verifier apps out there - generating a different QR could would definitely lead to misinterpretations on EU-level and would risk that people cannot enter venues or countries within the EU (and other member states). 

There are other ways that are working on right now the prevent the misuse.
These features will arrive with the upcoming releases -  so please stay tuned for more details.

Thank you again for participating 👍 🥳

**Comment by Kurt57** [comment]
@crownedsimon did you test our new warning when adding certificates of several persons?

Can we closes this issue?

**Comment by timokoenig** [comment]
Just my opinion but I don't think the "warning" is a good implementation. You get this info only twice and for all other certificates / persons can be added without it.

**Comment by Kurt57** [comment]
On the one hand you are absolutely right, on the other hand this warning should not disturb the user when using the app. I think the UX designers are trying to find the best solution for all the millions of users. A compromise.

**Comment by timokoenig** [comment]
I completely disagree that this disturbs the user when using the app. How often does the average user adds a new person? Even if this is a father that add three of his kids then he will get it three times and never again. On the other hand if a person at the restaurant scans a new person he will get it only twice which does not make sense at all.

**Comment by Kurt57** [comment]
Thank you for your opinion.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
