### ISSUE TITLE
QR code scanning view identical in CovPass and Check app

### ISSUE THREAD

**Issue by moabits** [Digitaler-Impfnachweis/covpass-ios#67]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

Cross-Reference: #66, https://github.com/Digitaler-Impfnachweis/covpass-android/issues/103, https://github.com/corona-warn-app/cwa-wishlist/issues/666, and https://github.com/corona-warn-app/cwa-wishlist/issues/601

## Current Implementation
Currently, the screens for adding a certificate (CovPass app) and checking a certificate (CovPass Check app) look identical, as can be seen below. This has two issues.

1. For a person showing their certificate at a restaurant for example, there is no way to distinguish if the inspector erroneously or maliciously uses the CovPass app or the CovPass Check app. On that view, there is simply no visual difference.

2. At the same time, the inspector likely uses their private smartphone and has both apps installed. Because of little difference in the app icons and general design, they could unconsciously open the wrong app and tap on the first primary button on the home screen (which is then either "+" in CovPass or "Scan certificate" in CovPass Check) and land on the QR code scanning screen. Again, here there is then no visual difference between the two apps.

<img src="https://user-images.githubusercontent.com/45351488/142865227-f99f20ea-a5a9-4a03-ac87-eb524ed37e97.PNG" width="200" title="CovPass Check"> <img src="https://user-images.githubusercontent.com/45351488/142865238-3a103b1a-be8c-473d-b6a2-c30b3685898f.PNG" width="200" title="CovPass">

Do you see a any difference here? One screen verifies your certificate, the other saves it to your phone.
I'd consider this a bad user experience, as the action is unclear. 

## Suggested Enhancement
Add a label or graphic to this view in both apps, that clearly distinguish the action to be taken when scanning a QR code.
For example, by adding a navigation bar with "Add certificate" vs. "Validate certificate" or some distinct icons on the screen.

<img src="https://user-images.githubusercontent.com/45351488/142865907-65665dfd-31ea-43cc-ae35-dbe89a3d8ba4.PNG" width="200" title="Suggestion">

## Expected Benefits
With this enhancement, both the checkee and the inspector can validate that they use the correct app and what action will be performed, even when on the QR code scanning screen.

**Comment by DanielMandea** [comment]
@timokoenig if at some point there will be a decision to move fwd with this enhancement please let me know if there is any need from my side to update Scanner package.

**Comment by timokoenig** [comment]
@DanielMandea at the moment there is no need but I or @alexcimander will let you know

**Comment by alexcimander** [comment]
Hey everyone,

we are currently working on improvements how we can prevent the usage of the CovPass as verifier-app - we will provide more details soon about and we are also discussing the idea of an overlay!

Thank you for your effort! :-) 

Hear you soon!

**Comment by moabits** [comment]
@Julius-W This is a known issue, please see #71 and related issues for more information.

**Comment by jleufgen** [comment]
@moabits thanks for the hint - can you please look at the improvement with the latest update? :)

**Comment by Ein-Tim** [comment]
@jleufgen 

The scanning view is still identical, isn't it.

**Comment by timokoenig** [comment]
yup nothing changed

**Comment by Ein-Tim** [comment]
I guess @jleufgen referst to the new feature that CovPass warns when adding certificates from more than 9 different people.

**Comment by jleufgen** [comment]
@Ein-Tim that's right, the person limitation is implemented with the new update and will be further improved in 1.16 :)

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
