### ISSUE TITLE
clearer UI difference between "cert invalid" and "cert not supported"

### ISSUE THREAD

**Issue by symbolisch1234** [Digitaler-Impfnachweis/covpass-ios#69]
## Current Implementation
Today i was called because the entrance scanned the cert of a person from the UK using the official NHS app. CovPassCheck categorised the cert as invalid. I think this might be related to #57, a few minutes later we scanned a french cert and it worked.

## Suggested Enhancement
Make the UI experience much clearer. There should be an obvious distinction between "This kind of cert is not supported" (YELLOW) and "This cert is supported, but invalid" (RED). At the moment both look basically identical. Ideally, the error message would even tell you how to check this other kind of cert, but i can see this being a lot of work. Thus i am asking only for a clearer distinction.

## Expected Benefits
Quite a number of people using CovPassCheck have very little knowledge of IT and certificates and no knowledge of the EU and certificates and all the intricacies connected. For such a person, given the current user experience, the NHS certificate seems like it is invalid and entry should be refused. However, given the person has a valid vaccination certificate, entry should actually NOT be refused.

**Comment by timokoenig** [comment]
@symbolisch1234 CovPassCheck already has two different error messages for those cases and they also list a few possible reasons

Technical Errors
https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/61ffab4fbde9ad89916229a7813348504578f916/Source/CovPassCheckApp/Source/Resources/Locale/en.lproj/Localizable.strings#L157

Other Errors
https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/61ffab4fbde9ad89916229a7813348504578f916/Source/CovPassCheckApp/Source/Resources/Locale/en.lproj/Localizable.strings#L171

**Comment by jleufgen** [comment]
Thank's @timokoenig for explanation. @symbolisch1234 is the answer enough for you or do you have further questions on this Topic? :-)

**Comment by symbolisch1234** [comment]
i am aware the two states give different error messages.

i just wanted to ask for the difference to be made more clear. the difference between "this is an invalid cert" and "this qr code is not one we can check" is a huge one, and it looks so similar, that untrained people at the door confuse them. 

that's all.

thanks for all your work.

**Comment by timokoenig** [comment]
Maybe something like this would help

Invalid certificates -> Red
Wrong or technically invalid certificates -> gray

**Comment by timokoenig** [comment]
With the upcoming version 1.34 of CovPassCheck, the result screen has different colored icons. I would consider this ticket as resolved.
