### ISSUE TITLE
Covpass Check does not recognize official certificate / QR code from Portugal

### ISSUE THREAD

**Issue by ghowen** [Digitaler-Impfnachweis/covpass-ios#7]
I just scanned my official vaccination certificate issued by the Portuguese health system today. 

The app then shows an error message saying that the QR code was not recognized and that the QR code does not belong to a digital Covid certificate of the EU. 

I have no idea if this is a problem with the Portuguese QR code or the Covpass Check app, but I would love the app to recognize my Portuguese certificate next time I travel to Germany. 

Screenshot: 
![962FB0D0-126C-437F-A1E1-EBE91DA61AB2_1_105_c](https://user-images.githubusercontent.com/390784/122563824-91f06c80-d03c-11eb-9a13-01de36c866f8.jpeg)

**Comment by thomasaugsten** [comment]
Did you test the certificate also with the Corona-Warn-App?

**Comment by timokoenig** [comment]
@ghowen which version of CovPassCheck did you use?

**Comment by ghowen** [comment]
1.1.3 (4) downloaded from the App Store today.

**Comment by SebastianRuecker** [comment]
@ghowen
Are you using passcode / faceid to unlock your iphone?

**Comment by ghowen** [comment]
@SebastianRuecker I am using TouchID. It's an iPhone SE 2 with lastest version of iOS.

**Comment by timokoenig** [comment]
Since yesterday there is a new version available in the App Store that removed the schema version check from the Digital Green Certificate data model. This should fix a variety of certificates from other EU countries who already use a newer version of the data model.

I will have a closer look to the data model from Portugal if that still doesn't fix your issue.

**Comment by ghowen** [comment]
@timokoenig Thanks. I just checked and the Portuguese code still does **not** work with 1.1.4 (1). The error message is the same as in https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/7#issue-924877309.

**Comment by thinkberg** [comment]
Updated and automatic updates are going to be in place until end of the week.

**Comment by ghowen** [comment]
I can confirm it now works with 1.3.0 (1). 

It does not work yet with CovPass itself, but that might be too much to ask. Or is CovPass also aiming at compatibility on the EU level?
