### ISSUE TITLE
Still showing that my QR code is not valid

### ISSUE THREAD

**Issue by YahyaDevelop** [Digitaler-Impfnachweis/covpass-ios#70]
Hello,

I have tried the live app on AppStore to scan my QR code and it is fine and shows my info.

Then I clone the project and copy the PROD certificates to the CovPassCommon, when I try scanning the code it still shows this message:

**COVID certificate does not have a valid signature**
This certificate might have been issued by an unauthorised organisation or the app might not have been updated. For the latter, please connect to the internet and try again later. (Error 412).

![IMG_8748](https://user-images.githubusercontent.com/14359174/143995904-b462ee51-3d00-4869-ab0f-3c8428c28751.PNG)

Anything else should I do?

Thank you for your help

**Comment by Ein-Tim** [comment]
I recommend you take a look at #63.

**Comment by timokoenig** [comment]
As @Ein-Tim already said, you will find your answer in #63

**Comment by YahyaDevelop** [comment]
Thank you very much @Ein-Tim , It is worked
