### ISSUE TITLE
Wrong expiration date for certificate

### ISSUE THREAD

**Issue by gotcha9999** [Digitaler-Impfnachweis/covpass-ios#72]
Expiration date of a certificate seems to be calculated from the date when the data is submitted to the RKI to get the digital certificate and not from the date of vaccination.

Person 1:
- Vaccination date 22.11.2021
- Submission date at the pharmacy 02.12.2021
-> certificate valid until 02.12.2022 (has to be 22.11.2022!)

Person 2:
- Vaccination date 01.12.2021
- Submission date at doxtor's office 01.12.2021
-> certificate valid until 01.12.2022

**Comment by Ein-Tim** [comment]
There is a [FAQ](https://digitaler-impfnachweis-app.de/en/faq/) entry on this: 

"**How long is the digital vaccination certificate valid?**"

"The EU digital vaccination certificate is currently valid in Germany for one year from the date of issue.
The recognition of the certificates abroad also depends on the different requirements of the EU countries. To be on the safe side, please visit https://reopen.europa.eu/de."

So this is not a bug, but a feature. (-;

**Comment by gotcha9999** [comment]
Thanks for the quick answer. But this treatment for Germany really makes no sense 🙃.
