### ISSUE TITLE
CovpassCheck App displaying not updating check rules connected by wifi

### ISSUE THREAD

**Issue by Gurumosch** [Digitaler-Impfnachweis/covpass-ios#77]
Environment:
IOS: 15.1
Iphone X, SE

CovpassCheck App 1.13 (4)

Test scenario:
Checking an actual vac certificate failed, even corona warn app is showing it valid
The date of check rules is displayed the current correct date. Refreshing the rule date in menu succeeds very quick.
After refresh the certificate is still unvalid.

Switching wifi off and refreshing the rules again takes a bit longer
After refresh on celular network the date/time is actual an the checking of the certificate is running successful.

Suggestion:
The refresh of the rule data could be blocked by a firewall rule. The app doesn't notifiy the user that the data hasn't been refreshed. Also the date/time is set to the check date even if no new data was retrieved:

Possible Solution:
Warn user that the data could not been retrieved
Dont refresh the check date/time

**Comment by alexcimander** [comment]
Hi Gurumosch,
thank you for your feedback! Please help us a bit to understand the situation. From what I got you are:

1. first connected to the Wifi and the rules are outdated (e.g. older than 24h)
2. you want to check your cert --> invalid (and this is not the result you are expecting?)
3. you are trying to update the rules using the "manual update" in the settings --> update seems successful
4. you are checking again -> invalid (and this is again not the result you are expecting)
5. now you switch to celluar network and start manual update ones more --> seems successful
6. now you check your certificate one last time and the result is: "valid"

Did I get that right? Thank you! 👍

**Comment by Gurumosch** [comment]
> Hi Gurumosch, thank you for your feedback! Please help us a bit to understand the situation. From what I got you are:
> 
> 1. first connected to the Wifi and the rules are outdated (e.g. older than 24h)
> 2. you want to check your cert --> invalid (and this is not the result you are expecting?)
> 3. you are trying to update the rules using the "manual update" in the settings --> update seems successful
> 4. you are checking again -> invalid (and this is again not the result you are expecting)
> 5. now you switch to celluar network and start manual update ones more --> seems successful
> 6. now you check your certificate one last time and the result is: "valid"
> 
> Did I get that right? Thank you! 👍

Hi,
i tried it again i think i have to clarify it a bit. 
The datetime value seems to be correct. The Problem is that the check rules were not being updated perhaps because of firewall restrictions in out company network. If you then start the manual update the progress indicator is displayed and hidden very fast but the rules are not updated. The problem is now that you don't get any notification, that the check rules are outdated and could not been refreshed. So The user might think everything ist correct by app site but checking new certificates will display the unvalid message.
This is a critical behavior in companies where the covpass app is used to fulfill the 3G rules. Unexperienced users might deny the entry because of an unvalid certificate which is not invalid (just by outdated check rules).
The CR would be to mark outdated check rules (with a red indicator for instance) and a hint text that because of outdated rules the check result could not be correct.
i hope i explained it understandable.
Thank you!

**Comment by Kurt57** [comment]
@Gurumosch is this problem still alive or can we close this issue?

**Comment by Kurt57** [comment]
I close this issue because of no response after long time.
