### ISSUE TITLE
Universal Links support

### ISSUE THREAD

**Issue by cyptus** [Digitaler-Impfnachweis/covpass-ios#79]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The app does not support universal links

## Suggested Enhancement
Add support for universal links

## Expected Benefits
Business Apps do provide management portals to companies where they do their daily work.
A new task for this daily work is checking covid certificates.
To make it easy it would be a great benefit if such apps could just link to a universal link that do opens the CovPass app directly (on the scanner page?).

See also: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/130

**Comment by oliver-steinbrecher** [comment]
Hello Cyptus, 

can you describe the use-case in more detail ? I need to understand how the apps are interfering with each other . Keep also on mind that we have to kind of Apps CovPass and CovPass Check . The later one is meant to be used for validation use cases.

**Comment by cyptus** [comment]
Hi @oliver-steinbrecher, sure:
Almost every company which do provide services or goods to public (like retail, restaurants, bakery's, zoos, ...) do have management software tools for their specific daily work.
It's not a special requirement for their leading software to be able to link for sub tasks to different apps.
For example this could be for ordering new material from special providers, switching the music in a music player app or booking working times.
A new task for these companies is to check the Covid certificates from their customers.
As employees are used to their leading software as working interface, they do search a functionality right there to scan certificates.
This could be a new implementation in their own software or a link to another app.
This is where an official Covid check app comes into play.
As it is not the goal to implement a own scanner for Covid certificates into each of these management softwares, a short link in these tools to an installed app of CovPass Check would enough to lead employees to the right place from their usual working Interface.
Technical speaking this would be a button which calls a universal link / deep link to open the scanner function of CovPass Check.

What's the benefit?
Users can work with their normal interface and a easy way is provided to call a full functional Covid scan app. 
If this process gets to complicated by opening homescreen, searching for other apps and so on, there will be less certificates get scanned by employees.

**Comment by jleufgen** [comment]
[https://github.com/Digitaler-Impfnachweis/covpass-android/issues/130 ](url)

**Comment by jleufgen** [comment]
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/130

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
