### ISSUE TITLE
Use local time rather than UTC Time

### ISSUE THREAD

**Issue by janmoritzmeyer0210** [Digitaler-Impfnachweis/covpass-ios#8]
The Apps (Covpass and Covpass Check) only recognize the full vaccination after 02:00 AM German Time on 15. day after vaccination, so I would guess you currently use the UTC time instead of the local time
![image](https://user-images.githubusercontent.com/70198091/122656600-6369b300-d15c-11eb-8081-9eb1b023a37a.png)
![image](https://user-images.githubusercontent.com/70198091/122656603-695f9400-d15c-11eb-8e82-26cdf4b635c6.png)

**Comment by timokoenig** [comment]
This has already been fixed and will be available with the next upload

**Comment by timokoenig** [comment]
Version 1.3 just has been released in the AppStore which fixes the issue
