### ISSUE TITLE
Not yet valid certificate gets set as default and shown as valid

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#82]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- OS version: 15.2 RC
- App version: 1.13 (5)

## Describe the bug

I recently got boostered and immediately scanned the code. This new code gets set as the default and shown with a green checkmark. But when scanned with CovPassCheck it says that it is not yet valid diente not being 14 days old.

Manually selecting the first vaccination (1/1 J&J) scans as valid with CovPassCheck.

CovPass should check that the new certificate is not yet valid and show the old one instead. Maybe show a warning icon next to the certificate.

![54D917F2-98F1-475D-AF56-8B1F410ED500](https://user-images.githubusercontent.com/16278233/145400053-81b954ad-3ae0-47e4-b88c-97bb77016df2.jpeg)

**Comment by Ein-Tim** [comment]
Hi @Kamik423 

This seems very similar to #78, could you check if this is a duplicate?

**Comment by Kamik423** [comment]
Oops, when I first read that it sounded like the issue there was adding the code to CovPass which is not what happened for me so I decided to create a new issue. 

Yes, it appears to be a duplicate. Sorry for the hassle.
