### ISSUE TITLE
No Notifications during scanning QR-Code

### ISSUE THREAD

**Issue by stritti** [Digitaler-Impfnachweis/covpass-ios#85]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

If you show someone your QR-code to verify it, there are also displayed system notifications for example of Threema, Email etc. 
This could be read by the person which will verify the certificate and is a minor personal data protection issue.

## Suggested Enhancement

The system notifications should be blocked while QR-code is shown. Like it is done at Wallet App.

## Expected Benefits

Personal data is protected against foreign person verifying the certificates.

**Comment by moabits** [comment]
AFAIK this is not possible on iOS. You could try the "Do not disturb" mode if it is a problem for you.

**Comment by stritti** [comment]
Hm, I think it should be possible somehow. For example Apps of airlines use I think special popups where also the display is set to high contrast. 
Maybe @Apple has to allow it for the app.

Switching to „Do not disturb“ is not a safe work around.

**Comment by timokoenig** [comment]
There is a difference between setting the screen contrast and disabling the notifications. An app itself can not disable the system notifications. There might be a special entitlement from Apple that allows the app to disable it but this can only be issued by them. Maybe the team can have a quick call with Apple to try their luck but until then there is no way of doing it.

**Comment by alexcimander** [comment]
hey everyone,

thank you @stritti for your suggestion. @timokoenig good call! With entitlements there might be a chance to disable notifications during the usage of the app. 

I will let you know if this is a possibility 👍

**Comment by stritti** [comment]
great, @alexcimander, many thanks for the investigations.

Probably my tweet thread will help a little bit: https://twitter.com/_stritti_/status/1470853205806489613?s=21

**Comment by alexcimander** [comment]
Thank you @stritti - we will get back to you 👍 💯

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
