### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by nklsbckmnn** [Digitaler-Impfnachweis/covpass-ios#86]
The app could display the number of imported certificates on the front page. Boostered certificates could count double or triple. There could be badges. Everybody could have a randomly generated avatar, like a cat or something.

**Comment by timokoenig** [comment]
Even though I would like to see some gamification in the app, number of imported certificates or any other shared data will not be possible. CovPass and CovPass Check are not allowed to sync any data or even anonymously collect analytics

**Comment by eliasweatherfield** [comment]
All of these can be done locally.

**Comment by timokoenig** [comment]
haha very interesting idea

**Comment by timokoenig** [comment]
I will link this issue here because they have some nice gamification features that might be interesting for CovPass as well: https://github.com/corona-warn-app/cwa-wishlist/issues/409

We should not only look at CovPass but more at CovPass Check. Some gamification could make the app more interesting to use

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
