### ISSUE TITLE
Prepare for EU change reg. booster vaccination certificates after 1/1 basic immunization (2/1) which will come into effect on 01.02.2022

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#87]
* [X] None of the other issue templates apply to this issue.

### This issue affects iOS & Android.

---

The EU decided that booster vaccinations should be certified as 2/1 starting from 01.02.2022 instead of, how it's handled currently, 2/2. 

See https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837 which says:

"In addition, today the Commission has also adapted the rules for the encoding of vaccination certificates. This is necessary to ensure that vaccination certificates showing completion of the primary series can always be distinguished from vaccination certificates issued following a booster dose.

Boosters will be recorded as follows:

- 3/3 for a booster dose following a primary 2-dose vaccination series.
- **2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person**." 

CovPass should be adapted so that it works properly with those certificates (i.e. not show "Impfung 2 von 1", the validity check for Germany needs to be adjusted, etc.).

This is an informational issue, feel free to move it to another repository (e.g. documentation), should you think it fits better there.

**Comment by alexcimander** [comment]
Hey @Ein-Tim,

we are currently working on the needed adjustments on the apps. It will be definitely part of the next releases so that we are prepared 👍

**Comment by Ein-Tim** [comment]
@alexcimander 

Can both CovPass as well as CovPassCheck deal with 2/1, 3/1, etc. certificates in version 1.17?

**Comment by Stevildo** [comment]
It looks like the probelm still exists in version 1.17 in CovPassCheck app!
CovPass App (V 1.17(1)) shows valid certificate with 2/1 but CovPassCheck App(V 1.17(1)) is not able to verify it.
Please fix it - thank you!

**Comment by Markkuuss** [comment]
Same here... 2/1 is shown as invalid.

Pleased fix ist.

**Comment by Ein-Tim** [comment]
@Markkuuss You mean when checking for validity for traveling to another country in CovPass or with CovPassCheck?

**Comment by Ein-Tim** [comment]
@Markkuuss 

Okay, thanks for the feedback.

@alexcimander Are the updated rules live already? Is it normal that 14 days waiting period are shown for 2/1 certs?

**Comment by Markkuuss** [comment]
For your information, my certificate is only a week old. Probably the information that a 2/1 certificate is immediately valid is missing.

**Comment by Ein-Tim** [comment]
@Markkuuss 

Yes I also think so, CWA was adapted in a hot fix to show immunity right away: https://github.com/corona-warn-app/cwa-app-android/pull/4764

**Comment by Ein-Tim** [comment]
@Markkuuss Did you check agin with version 1.18?

**Comment by timokoenig** [comment]
@Ein-Tim I guess now the certificate will be valid because it has been more than 14 days. Problem still remains since the rules have not been updated yet

**Comment by Markkuuss** [comment]
@Ein-Tim currently it does not work yet. But in 15 min 14 days have passed, then it will probably work. ;-)

**Comment by Ein-Tim** [comment]
I see no reason why I should still leave this issue open, the app has been prepared. For remaining issues, please open a new issue.
