### ISSUE TITLE
Prepare for EU change reg. period of validity of vaccination DCCs which will come into effect on 01.02.2022

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#88]
* [X] None of the other issue templates apply to this issue.

### This issue affects iOS & Android.

---

## Current Implementation
Vaccination certificates have a technical validity of one year since the issuing, after 6 months, the user is seeing a hint that they are eligible for a booster shot.    

## EU change which comes into effect on 01.02.2022

See this press statement from the European Commission: https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

It says:

"Today, the Commission adopted rules relating to the EU Digital COVID Certificate, establishing a binding acceptance period of 9 months (precisely 270 days) of vaccination certificates for the purposes of intra-EU travel."

So this means, after 9 moths, one who does not have a booster shot, can't use the vaccination DCC to travel intra-EU anymore.

## Prepare for this change

Make CovPass ready to display this information as soon as possible to prepare the user for this change so that the user has time to prepare and make an appointment for a booster shot. Make it clear that this change does not affect the vaccination status in Germany & the certificate will still be accepted for entry to e.g. restaurants.

CovPassCheck would probably need another mode, so that it denies vac. certs. which certify a vaccination which was more than 270 days ago (used by the people checking certificates on the border) & another mode which can be used in Germany where those certificates are not rejected.

**Comment by alexcimander** [comment]
Hey @Ein-Tim thank you for pointing it out! We will adapt the digital EU-Travel-Rules so that the 9 months will take effect for intra EU travels. When it comes to german internal rules we will provide needed information within the apps and FAQs.

Thank you! 👍

**Comment by oliver-steinbrecher** [comment]
See https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139

**Comment by mirabilos** [comment]
Isn’t this validity period only for the digital certificate? You can always get them re-issued at a local pharmacy, assuming they will still be of value to you this long after.

**Comment by Ein-Tim** [comment]
@mirabilos 

If you read the announcement by the EU I linked to in the OP, you can find more details on that.
I don't think they mean the technical validity here but that after 9 months the certificates are not sufficient for intra-eu traveling anymore.

**Comment by Ein-Tim** [comment]
@alexcimander 

Could you update us here what was changed to take this change into account?

**Comment by Ein-Tim** [comment]
This issue remains open until the travel rules have been updated.

**Comment by Ein-Tim** [comment]
Travel rules have been updated, this issue can be closed: https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=DE&rule=VR-DE-0004

**Comment by timokoenig** [comment]
I will leave #131 open since the test certificate rules are still wrong for entry and domestic

**Comment by Ein-Tim** [comment]
@timokoenig 

100% agreed but as this issue is only about the validity of vaccination certificates I closed it.
