### ISSUE TITLE
Version number in app and version number in App Store don't match

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#9]
The version numbers shown in the app (click on "?" in the top right corner) and the version numbers shown in the App Store don't match.
The version numbers should match.

| App Store | CovPass-App |  CovPassCheck-App |
|---|---|---|
|<img src="https://user-images.githubusercontent.com/67682506/122686108-d2541400-d20f-11eb-9e29-53457bdfb9d8.jpg" width="300">|<img src="https://user-images.githubusercontent.com/67682506/122686111-d4b66e00-d20f-11eb-906b-d225096d244b.PNG" width="300">|<img src="https://user-images.githubusercontent.com/67682506/122686110-d41dd780-d20f-11eb-9f8f-7348692dba2c.PNG" width="300">|

**Comment by timokoenig** [comment]
This has already been addressed and will be fixed with the next upload

**Comment by timokoenig** [comment]
Version 1.3 just has been released in the AppStore which fixes the issue

**Comment by Ein-Tim** [comment]
Confirm fix.
