### ISSUE TITLE
Fix duplicate names of exported certificates

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#90]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When the user exports a certificate the name of the certificate is always the same "Certificate-Foo-Bar.pdf". This causes a problem when the user tries to export all certificates because the previous file might get overwritten.

## Steps to reproduce the issue

1. Export first certificate
2. Export second certificate with the same name

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8ebcb284504c22d40235435cd609409163221ca9/Source/CovPassApp/Source/Scenes/PDF%20Export/PDFExportViewController.swift#L89

## Expected behaviour

Every certificate has a unique name

## Possible Fix

Include the certificate type and number of doses in the certificate, or maybe a timestamp

**Comment by timokoenig** [comment]
See https://github.com/Digitaler-Impfnachweis/covpass-android/issues/158 for initial bug report

**Comment by timokoenig** [comment]
Fix should be applied to CovPass Android as well

**Comment by alexcimander** [comment]
Hey @timokoenig, thank you and happy new year! I created a ticket for it 👍

**Comment by timokoenig** [comment]
Closing; I changed the filename for version 1.35
