### ISSUE TITLE
Alternate check modes

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#96]
Currently the CovPassCheckApp uses a 3G mode, where it grants a green checkmark to any vaccination, recovery or test. 

Multiple establishments such as restaurants however require someone to be 2G, so a test certificate alone does not permit entry. In Bavaria recreational establishments now are 2G+ where one has to be vaccinated AND tested or boostered.

The CovPassCheckApp currently is not sufficient for these cases; scanning the QR code alone is not enough. People will again take your phone and scroll through the list of entries, checking the date. This negates the promised privacy benefits of the CovPassCheckApp and fails to verify the entries are actually legit and not for example from a fork of the app that always shows full entries (this used to exist but apparently the repo has been deleted). Additionally handing your phone over is very suboptimal.

Thus the CovPassCheckApp should either display what it just scanned (vaccinated/boostered/tested) or better even have a mode selector like:

```
Valid checks:
[ ] Test
[ ] Vaccination
[X] Booster
[X] Vaccination + Test
```

Where the latter option would require two scans, confirming that the person is vaccinated in the first scan and then require the operator to either scan the test certificate or visually confirm it in a PDF (since it is non-trivial to get test results into the CovPassApp).

Additionally regional rules would have to be selected as well. In Germany a booster would be either a 3/3 or 2/1 certificate (beginning February) but Bavaria requires two boosters for J&J, 2/1 is not enough to be counted as boostered. (This could be either done via geo-fencing or via a setting. Maybe initialize the setting with geo-fencing. This would prevent problems for the border-force for example).

**This is not just an enhancement request but a necessary step for the CovPassApp to continue to fulfill the tasks it was design to.** It worked fine for the brief window that 3G was the default here in Germany, but now we moved on to more complicated systems.

**Comment by timokoenig** [comment]
This has already been discussed in other tickets. It will be part of release 1.17

see https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139

**Comment by Kamik423** [comment]
Thanks, I did not think to check the Android repo.
