### ISSUE TITLE
Information screen when rules get updated

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#98]
Somehow related to https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97

## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

The user does not see any rule changes that might affect him.

## Suggested Enhancement

When one or more German rules get updated the user gets a small hint or information screen displaying all rule changes that might affect him. This screen can display the old rule and shows the diff to the updated rule or any new rules. This screen can highlight rules that are related to the certificates on the local device.

The app can detect those rule changes when it updates the local rule set.

## Expected Benefits

The user gets important information about rule changes earlier that might have get him rejected at the border or any other entry.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
