### ISSUE TITLE
English FAQ referenced for German version

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#99]
The current implementation has a static FAQ link that references the English version for an app that is in German. This should be dynamically based on the users language DE or EN.

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8b25bcfcdc0f108f8c74179a09e5ae1849f2b344/Source/CovPassApp/Source/Scenes/Certificates%20Overview/CertificatesOverviewRouter.swift#L20

**Comment by jleufgen** [comment]
@timokoenig thanks for the hint👍It will be fixed asap!

**Comment by timokoenig** [comment]
Still not fixed with version 1.18

**Comment by alexcimander** [comment]
Hey everyone, 

due to several priority-shifts this ticket just found its way into development. Sorry for the delay!

**Comment by Kurt57** [comment]
@timokoenig should be solved with 088ba09ee257f8eb5ccbf040c74282578010dd88
